# Issue 25974: py3: fix unnecessary map() in sage.calculus.riemann

archive/issues_025737.json:
```json
{
    "body": "This one silly fix took this module from 67 doctests failing to 100% passing on my python3 branch.\n\n**CC:**  @egourgoulhon\n\n**Branch/Commit:** [6b7e132b26f4d78d18fd338f880cd1d9cde973b4](https://github.com/sagemath/sagetrac-mirror/commit/6b7e132b26f4d78d18fd338f880cd1d9cde973b4)\n\n**Reviewer:** Kevin Dilks\n\n**Author:** Erik Bray\n\nIssue created by migration from https://trac.sagemath.org/ticket/25974\n\n",
    "closed_at": "2018-08-09T21:27:46Z",
    "created_at": "2018-07-30T11:43:54Z",
    "labels": [
        "component: python3",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-8.4",
    "title": "py3: fix unnecessary map() in sage.calculus.riemann",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/25974",
    "user": "https://github.com/embray"
}
```
This one silly fix took this module from 67 doctests failing to 100% passing on my python3 branch.

**CC:**  @egourgoulhon

**Branch/Commit:** [6b7e132b26f4d78d18fd338f880cd1d9cde973b4](https://github.com/sagemath/sagetrac-mirror/commit/6b7e132b26f4d78d18fd338f880cd1d9cde973b4)

**Reviewer:** Kevin Dilks

**Author:** Erik Bray

Issue created by migration from https://trac.sagemath.org/ticket/25974





---

archive/issue_events_232644.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-07-30T11:44:00Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25974#event-232644"
}
```



---

archive/issue_comments_402406.json:
```json
{
    "body": "<a id='comment:2'></a>\nPatchbot shows a lot of elliptic function methods and other things that may be related failing.",
    "created_at": "2018-07-30T16:59:59Z",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25974#issuecomment-402406",
    "user": "https://github.com/kevindilks"
}
```

<a id='comment:2'></a>
Patchbot shows a lot of elliptic function methods and other things that may be related failing.



---

archive/issue_events_232645.json:
```json
{
    "actor": "https://github.com/kevindilks",
    "created_at": "2018-07-30T16:59:59Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25974#event-232645"
}
```



---

archive/issue_events_232646.json:
```json
{
    "actor": "https://github.com/kevindilks",
    "created_at": "2018-07-30T16:59:59Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25974#event-232646"
}
```



---

archive/issue_comments_402407.json:
```json
{
    "body": "<a id='comment:3'></a>\nThat's quite a coincidence but I don't think it's related.  I believe those failures are due to a bug in uninstalling/reinstalling the sympow package.  I encountered the same recently myself.  I will run the tests locally just to be sure though.",
    "created_at": "2018-07-30T17:06:11Z",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25974#issuecomment-402407",
    "user": "https://github.com/embray"
}
```

<a id='comment:3'></a>
That's quite a coincidence but I don't think it's related.  I believe those failures are due to a bug in uninstalling/reinstalling the sympow package.  I encountered the same recently myself.  I will run the tests locally just to be sure though.



---

archive/issue_comments_402408.json:
```json
{
    "body": "<a id='comment:4'></a>\nYeah, I was able to confirm that these tests pass locally, but breaking the `sympow` executable breaks them.  This is due to #25856, but not this ticket.",
    "created_at": "2018-07-30T17:17:25Z",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25974#issuecomment-402408",
    "user": "https://github.com/embray"
}
```

<a id='comment:4'></a>
Yeah, I was able to confirm that these tests pass locally, but breaking the `sympow` executable breaks them.  This is due to #25856, but not this ticket.



---

archive/issue_events_232647.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-07-30T17:17:25Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25974#event-232647"
}
```



---

archive/issue_events_232648.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-07-30T17:17:25Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25974#event-232648"
}
```



---

archive/issue_comments_402409.json:
```json
{
    "body": "<a id='comment:5'></a>\nI also just ran the tests on my machine with no problems.",
    "created_at": "2018-07-30T18:43:09Z",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25974#issuecomment-402409",
    "user": "https://github.com/kevindilks"
}
```

<a id='comment:5'></a>
I also just ran the tests on my machine with no problems.



---

archive/issue_events_232649.json:
```json
{
    "actor": "https://github.com/kevindilks",
    "created_at": "2018-07-30T18:43:09Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25974#event-232649"
}
```



---

archive/issue_events_232650.json:
```json
{
    "actor": "https://github.com/kevindilks",
    "created_at": "2018-07-30T18:43:09Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25974#event-232650"
}
```



---

archive/issue_comments_402410.json:
```json
{
    "body": "**Reviewer:** Kevin Dilks",
    "created_at": "2018-07-30T18:43:09Z",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25974#issuecomment-402410",
    "user": "https://github.com/kevindilks"
}
```

**Reviewer:** Kevin Dilks



---

archive/issue_events_232651.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-08-09T21:27:46Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25974#event-232651"
}
```



---

archive/issue_events_232652.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-08-09T21:27:46Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/25974#event-232652"
}
```



---

archive/issue_comments_402411.json:
```json
{
    "body": "**Changing branch** from \"[u/embray/python3/sage-calculus-riemann/map](https://github.com/sagemath/sagetrac-mirror/tree/u/embray/python3/sage-calculus-riemann/map)\" to \"[6b7e132b26f4d78d18fd338f880cd1d9cde973b4](https://github.com/sagemath/sagetrac-mirror/commit/6b7e132b26f4d78d18fd338f880cd1d9cde973b4)\".",
    "created_at": "2018-08-09T21:27:46Z",
    "issue": "https://github.com/sagemath/sage/issues/25974",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/25974#issuecomment-402411",
    "user": "https://github.com/vbraun"
}
```

**Changing branch** from "[u/embray/python3/sage-calculus-riemann/map](https://github.com/sagemath/sagetrac-mirror/tree/u/embray/python3/sage-calculus-riemann/map)" to "[6b7e132b26f4d78d18fd338f880cd1d9cde973b4](https://github.com/sagemath/sagetrac-mirror/commit/6b7e132b26f4d78d18fd338f880cd1d9cde973b4)".
