# Issue 23055: cython does not pass self-tests on 32bit systems

archive/issues_022818.json:
```json
{
    "body": "See the log at https://sagedebianlive.metelu.net/pastebin/cython-0.25.2.p1.log\n\n\n**CC:**  @robertwb\n\n**Keywords:** sdl\n\n**Upstream:** Fixed upstream, in a later stable release.\n\n**Reviewer:** Thierry Monteil\n\nIssue created by migration from https://trac.sagemath.org/ticket/23055\n\n",
    "closed_at": "2019-08-22T06:45:27Z",
    "created_at": "2017-05-22T13:23:28Z",
    "labels": [
        "component: packages: standard",
        "bug",
        "invalid"
    ],
    "title": "cython does not pass self-tests on 32bit systems",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/23055",
    "user": "https://trac.sagemath.org/admin/accounts/users/tmonteil"
}
```
See the log at https://sagedebianlive.metelu.net/pastebin/cython-0.25.2.p1.log


**CC:**  @robertwb

**Keywords:** sdl

**Upstream:** Fixed upstream, in a later stable release.

**Reviewer:** Thierry Monteil

Issue created by migration from https://trac.sagemath.org/ticket/23055





---

archive/issue_comments_347881.json:
```json
{
    "body": "<a id='comment:1'></a>\nThe log is too big to be uploaded here, so let me put it temporarilly at the address: https://sagedebianlive.metelu.net/pastebin/cython-0.25.2.p1.log",
    "created_at": "2017-05-22T13:39:46Z",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/23055#issuecomment-347881",
    "user": "https://trac.sagemath.org/admin/accounts/users/tmonteil"
}
```

<a id='comment:1'></a>
The log is too big to be uploaded here, so let me put it temporarilly at the address: https://sagedebianlive.metelu.net/pastebin/cython-0.25.2.p1.log



---

archive/issue_comments_347882.json:
```json
{
    "body": "<a id='comment:2'></a>\nJust before the segmentation fault (line -20), there are tons of\n\n```\nException RuntimeWarning: RuntimeWarning(\"coroutine 'CoroutineTest.test_await_9.<locals>.bar' was never awaited\",) in <coroutine object at 0xb3848cd4>\n```",
    "created_at": "2017-05-22T13:42:34Z",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/23055#issuecomment-347882",
    "user": "https://trac.sagemath.org/admin/accounts/users/tmonteil"
}
```

<a id='comment:2'></a>
Just before the segmentation fault (line -20), there are tons of

```
Exception RuntimeWarning: RuntimeWarning("coroutine 'CoroutineTest.test_await_9.<locals>.bar' was never awaited",) in <coroutine object at 0xb3848cd4>
```



---

archive/issue_comments_347883.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -1 +1,2 @@\n-See the attached log `cython-0.25.2.p1.log`\n+See the log at https://sagedebianlive.metelu.net/pastebin/cython-0.25.2.p1.log\n+\n``````\n",
    "created_at": "2017-05-22T14:46:50Z",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/23055#issuecomment-347883",
    "user": "https://trac.sagemath.org/admin/accounts/users/tmonteil"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -1 +1,2 @@
-See the attached log `cython-0.25.2.p1.log`
+See the log at https://sagedebianlive.metelu.net/pastebin/cython-0.25.2.p1.log
+
``````




---

archive/issue_events_207394.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2017-06-11T09:46:32Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "label": "blocker",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/23055#event-207394"
}
```



---

archive/issue_comments_347884.json:
```json
{
    "body": "**Reviewer:** Thierry Monteil",
    "created_at": "2019-08-22T06:07:42Z",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/23055#issuecomment-347884",
    "user": "https://trac.sagemath.org/admin/accounts/users/tmonteil"
}
```

**Reviewer:** Thierry Monteil



---

archive/issue_comments_347885.json:
```json
{
    "body": "<a id='comment:6'></a>\nThis fixed by recent releases, see the log at \u200bhttps://sagedebianlive.metelu.net/pastebin/cython-0.29.5.p0.log",
    "created_at": "2019-08-22T06:07:42Z",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/23055#issuecomment-347885",
    "user": "https://trac.sagemath.org/admin/accounts/users/tmonteil"
}
```

<a id='comment:6'></a>
This fixed by recent releases, see the log at â€‹https://sagedebianlive.metelu.net/pastebin/cython-0.29.5.p0.log



---

archive/issue_events_207395.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/tmonteil",
    "created_at": "2019-08-22T06:07:42Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/23055#event-207395"
}
```



---

archive/issue_comments_347886.json:
```json
{
    "body": "**Changing keywords** from \"\" to \"sdl\".",
    "created_at": "2019-08-22T06:07:42Z",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/23055#issuecomment-347886",
    "user": "https://trac.sagemath.org/admin/accounts/users/tmonteil"
}
```

**Changing keywords** from "" to "sdl".



---

archive/issue_comments_347887.json:
```json
{
    "body": "<a id='comment:7'></a>\nThere should be a milestone for things fixed elsewhere, it is neither duplicate, nor invalid, nor wontfix.",
    "created_at": "2019-08-22T06:10:30Z",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/23055#issuecomment-347887",
    "user": "https://trac.sagemath.org/admin/accounts/users/tmonteil"
}
```

<a id='comment:7'></a>
There should be a milestone for things fixed elsewhere, it is neither duplicate, nor invalid, nor wontfix.



---

archive/issue_events_207396.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/tmonteil",
    "created_at": "2019-08-22T06:10:30Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "milestone": "sage-8.0",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/23055#event-207396"
}
```



---

archive/issue_events_207397.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/tmonteil",
    "created_at": "2019-08-22T06:10:30Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/23055#event-207397"
}
```



---

archive/issue_events_207398.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/tmonteil",
    "created_at": "2019-08-22T06:10:30Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/23055#event-207398"
}
```



---

archive/issue_comments_347888.json:
```json
{
    "body": "**Upstream:** Fixed upstream, in a later stable release.",
    "created_at": "2019-08-22T06:10:30Z",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/23055#issuecomment-347888",
    "user": "https://trac.sagemath.org/admin/accounts/users/tmonteil"
}
```

**Upstream:** Fixed upstream, in a later stable release.



---

archive/issue_events_207399.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2019-08-22T06:45:27Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/23055#event-207399"
}
```



---

archive/issue_events_207400.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2019-08-22T06:45:27Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/23055",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/23055#event-207400"
}
```
