# Issue 22537: Use Python 3 metaclass syntax in Cython code

archive/issues_022300.json:
```json
{
    "body": "\n\n**CC:**  @fchapoton\n\n**Branch/Commit:** [ba82671db9807e151a7ae5f72fe76c4456ab4c05](https://github.com/sagemath/sagetrac-mirror/commit/ba82671db9807e151a7ae5f72fe76c4456ab4c05)\n\n**Reviewer:** Fr\u00e9d\u00e9ric Chapoton\n\n**Author:** Jeroen Demeyer\n\nIssue created by migration from https://trac.sagemath.org/ticket/22537\n\n",
    "closed_at": "2017-03-10T23:12:58Z",
    "created_at": "2017-03-07T10:58:52Z",
    "labels": [
        "component: python3",
        "enhancement"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-7.6",
    "title": "Use Python 3 metaclass syntax in Cython code",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/22537",
    "user": "https://github.com/jdemeyer"
}
```


**CC:**  @fchapoton

**Branch/Commit:** [ba82671db9807e151a7ae5f72fe76c4456ab4c05](https://github.com/sagemath/sagetrac-mirror/commit/ba82671db9807e151a7ae5f72fe76c4456ab4c05)

**Reviewer:** Frédéric Chapoton

**Author:** Jeroen Demeyer

Issue created by migration from https://trac.sagemath.org/ticket/22537





---

archive/issue_events_202972.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-03-07T11:10:45Z",
    "event": "renamed",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "rename": {
        "from": "Use Python 3 metaclass syntax in Cython files",
        "to": "Use Python 3 metaclass syntax in Cython code"
    },
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22537#event-202972"
}
```



---

archive/issue_comments_336454.json:
```json
{
    "body": "**Branch:** [u/jdemeyer/use_python_3_metaclass_syntax_in_cython_files](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/use_python_3_metaclass_syntax_in_cython_files)",
    "created_at": "2017-03-07T11:11:54Z",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22537#issuecomment-336454",
    "user": "https://github.com/jdemeyer"
}
```

**Branch:** [u/jdemeyer/use_python_3_metaclass_syntax_in_cython_files](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/use_python_3_metaclass_syntax_in_cython_files)



---

archive/issue_comments_336455.json:
```json
{
    "body": "**Commit:** [ba82671db9807e151a7ae5f72fe76c4456ab4c05](https://github.com/sagemath/sagetrac-mirror/commit/ba82671db9807e151a7ae5f72fe76c4456ab4c05)",
    "created_at": "2017-03-07T11:12:06Z",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22537#issuecomment-336455",
    "user": "https://github.com/jdemeyer"
}
```

**Commit:** [ba82671db9807e151a7ae5f72fe76c4456ab4c05](https://github.com/sagemath/sagetrac-mirror/commit/ba82671db9807e151a7ae5f72fe76c4456ab4c05)



---

archive/issue_comments_336456.json:
```json
{
    "body": "<a id='comment:3'></a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/ba82671db9807e151a7ae5f72fe76c4456ab4c05\">ba82671</a></td><td><code>Use Python 3 metaclass syntax</code></td></tr></table>\n",
    "created_at": "2017-03-07T11:12:06Z",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22537#issuecomment-336456",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:3'></a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/ba82671db9807e151a7ae5f72fe76c4456ab4c05">ba82671</a></td><td><code>Use Python 3 metaclass syntax</code></td></tr></table>




---

archive/issue_events_202973.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-03-07T11:12:06Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22537#event-202973"
}
```



---

archive/issue_comments_336457.json:
```json
{
    "body": "<a id='comment:4'></a>\nThis seems to break things quite badly.. at least the patchbot shows a rather strange result..",
    "created_at": "2017-03-07T16:33:55Z",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22537#issuecomment-336457",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:4'></a>
This seems to break things quite badly.. at least the patchbot shows a rather strange result..



---

archive/issue_comments_336458.json:
```json
{
    "body": "<a id='comment:5'></a>\nReplying to [@fchapoton](#comment%3A4):\n> This seems to break things quite badly.. at least the patchbot shows a rather strange result..\n\nI don't know what you are seeing. I see just one timeout in `src/sage/doctest/test.py`",
    "created_at": "2017-03-07T20:50:31Z",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22537#issuecomment-336458",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:5'></a>
Replying to [@fchapoton](#comment%3A4):
> This seems to break things quite badly.. at least the patchbot shows a rather strange result..

I don't know what you are seeing. I see just one timeout in `src/sage/doctest/test.py`



---

archive/issue_comments_336459.json:
```json
{
    "body": "<a id='comment:6'></a>\nwell, my patchbot shortlog contains (among many other bad-looking things)\n\n```\nAttaching gdb to process id 45443.\n\nSaved trace to /home/u1/chapoton/.sage/crash_logs/crash_TkiqJY.log\n------------------------------------------------------------------------\nUnhandled SIGABRT: An abort() occurred.\nThis probably occurred because a *compiled* module has a bug\nin it and is not properly wrapped with sig_on(), sig_off().\nPython will now terminate.\n```",
    "created_at": "2017-03-07T20:53:05Z",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22537#issuecomment-336459",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:6'></a>
well, my patchbot shortlog contains (among many other bad-looking things)

```
Attaching gdb to process id 45443.

Saved trace to /home/u1/chapoton/.sage/crash_logs/crash_TkiqJY.log
------------------------------------------------------------------------
Unhandled SIGABRT: An abort() occurred.
This probably occurred because a *compiled* module has a bug
in it and is not properly wrapped with sig_on(), sig_off().
Python will now terminate.
```



---

archive/issue_comments_336460.json:
```json
{
    "body": "<a id='comment:7'></a>\nReplying to [@fchapoton](#comment%3A6):\n> well, my patchbot shortlog contains (among many other bad-looking things)\n\nIt seems that your patchbot is the only one, so then this ticket probably is not the cause.",
    "created_at": "2017-03-07T21:04:10Z",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22537#issuecomment-336460",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:7'></a>
Replying to [@fchapoton](#comment%3A6):
> well, my patchbot shortlog contains (among many other bad-looking things)

It seems that your patchbot is the only one, so then this ticket probably is not the cause.



---

archive/issue_comments_336461.json:
```json
{
    "body": "**Reviewer:** Fr\u00e9d\u00e9ric Chapoton",
    "created_at": "2017-03-07T21:46:51Z",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22537#issuecomment-336461",
    "user": "https://github.com/fchapoton"
}
```

**Reviewer:** Frédéric Chapoton



---

archive/issue_events_202974.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2017-03-07T21:46:51Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22537#event-202974"
}
```



---

archive/issue_events_202975.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2017-03-07T21:46:51Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22537#event-202975"
}
```



---

archive/issue_comments_336462.json:
```json
{
    "body": "<a id='comment:8'></a>\nok, last run of the patchbot is green and changes look good to me\n\nsetting to positive",
    "created_at": "2017-03-07T21:46:51Z",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22537#issuecomment-336462",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:8'></a>
ok, last run of the patchbot is green and changes look good to me

setting to positive



---

archive/issue_events_202976.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2017-03-10T23:12:58Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22537#event-202976"
}
```



---

archive/issue_events_202977.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "308c2b05ec37712c58f4d1922e6a3ac164259e3c",
    "created_at": "2017-03-10T23:12:58Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/22537#event-202977"
}
```



---

archive/issue_comments_336463.json:
```json
{
    "body": "**Changing branch** from \"[u/jdemeyer/use_python_3_metaclass_syntax_in_cython_files](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/use_python_3_metaclass_syntax_in_cython_files)\" to \"[ba82671db9807e151a7ae5f72fe76c4456ab4c05](https://github.com/sagemath/sagetrac-mirror/commit/ba82671db9807e151a7ae5f72fe76c4456ab4c05)\".",
    "created_at": "2017-03-10T23:12:58Z",
    "issue": "https://github.com/sagemath/sage/issues/22537",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/22537#issuecomment-336463",
    "user": "https://github.com/vbraun"
}
```

**Changing branch** from "[u/jdemeyer/use_python_3_metaclass_syntax_in_cython_files](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/use_python_3_metaclass_syntax_in_cython_files)" to "[ba82671db9807e151a7ae5f72fe76c4456ab4c05](https://github.com/sagemath/sagetrac-mirror/commit/ba82671db9807e151a7ae5f72fe76c4456ab4c05)".
