# Issue 26182: py3: fix doctests failures of sage/sets/disjoint_set.pyx

archive/issues_025945.json:
```json
{
    "body": "On https://patchbot.sagemath.org/ticket/0/ there are two failures for the file `sage/sets/disjoint_set.pyx` when run with Python 3:\n\n```\nsage -t --long src/sage/sets/disjoint_set.pyx\n**********************************************************************\nFile \"src/sage/sets/disjoint_set.pyx\", line 537, in sage.sets.disjoint_set.DisjointSet_of_integers.root_to_elements_dict\nFailed example:\n    d.root_to_elements_dict()\nExpected:\n    {1: [1], 2: [0, 2, 3], 4: [4]}\nGot:\n    {2: [0, 2, 3], 1: [1], 4: [4]}\n**********************************************************************\nFile \"src/sage/sets/disjoint_set.pyx\", line 829, in sage.sets.disjoint_set.DisjointSet_of_hashables.root_to_elements_dict\nFailed example:\n    e = d.root_to_elements_dict(); e\nExpected:\n    {0: [0], 2: [2, 3], 4: [1, 4]}\nGot:\n    {0: [0], 4: [1, 4], 2: [2, 3]}\n**********************************************************************\n2 items had failures:\n   1 of   5 in sage.sets.disjoint_set.DisjointSet_of_hashables.root_to_elements_dict\n   1 of   8 in sage.sets.disjoint_set.DisjointSet_of_integers.root_to_elements_dict\n    [241 tests, 2 failures, 0.39 s]\n```\n\n**CC:**  @fchapoton\n\n**Branch/Commit:** [5b4e968f450c992e3cbc74832d845a4f1c6a067f](https://github.com/sagemath/sagetrac-mirror/commit/5b4e968f450c992e3cbc74832d845a4f1c6a067f)\n\n**Reviewer:** Travis Scrimshaw\n\n**Author:** S\u00e9bastien Labb\u00e9\n\nIssue created by migration from https://trac.sagemath.org/ticket/26182\n\n",
    "closed_at": "2018-09-05T16:43:28Z",
    "created_at": "2018-09-02T21:49:57Z",
    "labels": [
        "component: doctest coverage",
        "minor",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-8.4",
    "title": "py3: fix doctests failures of sage/sets/disjoint_set.pyx",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/26182",
    "user": "https://github.com/seblabbe"
}
```
On https://patchbot.sagemath.org/ticket/0/ there are two failures for the file `sage/sets/disjoint_set.pyx` when run with Python 3:

```
sage -t --long src/sage/sets/disjoint_set.pyx
**********************************************************************
File "src/sage/sets/disjoint_set.pyx", line 537, in sage.sets.disjoint_set.DisjointSet_of_integers.root_to_elements_dict
Failed example:
    d.root_to_elements_dict()
Expected:
    {1: [1], 2: [0, 2, 3], 4: [4]}
Got:
    {2: [0, 2, 3], 1: [1], 4: [4]}
**********************************************************************
File "src/sage/sets/disjoint_set.pyx", line 829, in sage.sets.disjoint_set.DisjointSet_of_hashables.root_to_elements_dict
Failed example:
    e = d.root_to_elements_dict(); e
Expected:
    {0: [0], 2: [2, 3], 4: [1, 4]}
Got:
    {0: [0], 4: [1, 4], 2: [2, 3]}
**********************************************************************
2 items had failures:
   1 of   5 in sage.sets.disjoint_set.DisjointSet_of_hashables.root_to_elements_dict
   1 of   8 in sage.sets.disjoint_set.DisjointSet_of_integers.root_to_elements_dict
    [241 tests, 2 failures, 0.39 s]
```

**CC:**  @fchapoton

**Branch/Commit:** [5b4e968f450c992e3cbc74832d845a4f1c6a067f](https://github.com/sagemath/sagetrac-mirror/commit/5b4e968f450c992e3cbc74832d845a4f1c6a067f)

**Reviewer:** Travis Scrimshaw

**Author:** Sébastien Labbé

Issue created by migration from https://trac.sagemath.org/ticket/26182





---

archive/issue_events_234232.json:
```json
{
    "actor": "https://github.com/seblabbe",
    "created_at": "2018-09-02T22:06:32Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26182",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26182#event-234232"
}
```



---

archive/issue_comments_405872.json:
```json
{
    "body": "**Commit:** [5b4e968f450c992e3cbc74832d845a4f1c6a067f](https://github.com/sagemath/sagetrac-mirror/commit/5b4e968f450c992e3cbc74832d845a4f1c6a067f)",
    "created_at": "2018-09-02T22:06:32Z",
    "issue": "https://github.com/sagemath/sage/issues/26182",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26182#issuecomment-405872",
    "user": "https://github.com/seblabbe"
}
```

**Commit:** [5b4e968f450c992e3cbc74832d845a4f1c6a067f](https://github.com/sagemath/sagetrac-mirror/commit/5b4e968f450c992e3cbc74832d845a4f1c6a067f)



---

archive/issue_comments_405873.json:
```json
{
    "body": "**Author:** S\u00e9bastien Labb\u00e9",
    "created_at": "2018-09-02T22:06:32Z",
    "issue": "https://github.com/sagemath/sage/issues/26182",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26182#issuecomment-405873",
    "user": "https://github.com/seblabbe"
}
```

**Author:** Sébastien Labbé



---

archive/issue_comments_405874.json:
```json
{
    "body": "<a id='comment:1'></a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/5b4e968f450c992e3cbc74832d845a4f1c6a067f\">5b4e968</a></td><td><code>26182: fixing dict ordering issues for python 3 in doctest</code></td></tr></table>\n",
    "created_at": "2018-09-02T22:06:32Z",
    "issue": "https://github.com/sagemath/sage/issues/26182",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26182#issuecomment-405874",
    "user": "https://github.com/seblabbe"
}
```

<a id='comment:1'></a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/5b4e968f450c992e3cbc74832d845a4f1c6a067f">5b4e968</a></td><td><code>26182: fixing dict ordering issues for python 3 in doctest</code></td></tr></table>




---

archive/issue_comments_405875.json:
```json
{
    "body": "**Branch:** [u/slabbe/26182](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/26182)",
    "created_at": "2018-09-02T22:06:32Z",
    "issue": "https://github.com/sagemath/sage/issues/26182",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26182#issuecomment-405875",
    "user": "https://github.com/seblabbe"
}
```

**Branch:** [u/slabbe/26182](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/26182)



---

archive/issue_events_234233.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-09-03T02:15:02Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/26182",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26182#event-234233"
}
```



---

archive/issue_events_234234.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-09-03T02:15:02Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26182",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26182#event-234234"
}
```



---

archive/issue_comments_405876.json:
```json
{
    "body": "**Reviewer:** Travis Scrimshaw",
    "created_at": "2018-09-03T02:15:02Z",
    "issue": "https://github.com/sagemath/sage/issues/26182",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26182#issuecomment-405876",
    "user": "https://github.com/tscrim"
}
```

**Reviewer:** Travis Scrimshaw



---

archive/issue_comments_405877.json:
```json
{
    "body": "<a id='comment:2'></a>\nLGTM.",
    "created_at": "2018-09-03T02:15:02Z",
    "issue": "https://github.com/sagemath/sage/issues/26182",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26182#issuecomment-405877",
    "user": "https://github.com/tscrim"
}
```

<a id='comment:2'></a>
LGTM.



---

archive/issue_events_234235.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-09-05T16:43:28Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/26182",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26182#event-234235"
}
```



---

archive/issue_events_234236.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "1a152c0bdf482c412b095f67dd0e079bf5626304",
    "created_at": "2018-09-05T16:43:28Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/26182",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26182#event-234236"
}
```



---

archive/issue_comments_405878.json:
```json
{
    "body": "**Changing branch** from \"[u/slabbe/26182](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/26182)\" to \"[5b4e968f450c992e3cbc74832d845a4f1c6a067f](https://github.com/sagemath/sagetrac-mirror/commit/5b4e968f450c992e3cbc74832d845a4f1c6a067f)\".",
    "created_at": "2018-09-05T16:43:28Z",
    "issue": "https://github.com/sagemath/sage/issues/26182",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26182#issuecomment-405878",
    "user": "https://github.com/vbraun"
}
```

**Changing branch** from "[u/slabbe/26182](https://github.com/sagemath/sagetrac-mirror/tree/u/slabbe/26182)" to "[5b4e968f450c992e3cbc74832d845a4f1c6a067f](https://github.com/sagemath/sagetrac-mirror/commit/5b4e968f450c992e3cbc74832d845a4f1c6a067f)".
