# Issue 26946: cardinality of finite multivariate polynomial quotients is broken

archive/issues_026709.json:
```json
{
    "body": "\n```\nsage: R.<a> = PolynomialRing(GF(2)); R.quotient((a^2+a)*R).cardinality()\n4\nsage: R.<a,b> = PolynomialRing(GF(2)); R.quotient((a^2+a, b^2+b)*R).cardinality()\n---------------------------------------------------------------------------\nAttributeError                            Traceback (most recent call last)\n<ipython-input-12-0d4ecbf62612> in <module>()\n----> 1 R = PolynomialRing(GF(Integer(2)), names=('a', 'b',)); (a, b,) = R._first_ngens(2); R.quotient((a**Integer(2)+a, b**Integer(2)+b)*R).cardinality()\n\n/home/martin/sage-develop/local/lib/python2.7/site-packages/sage/rings/ring.pyx in sage.rings.ring.Ring.cardinality (build/cythonized/sage/rings/ring.c:9050)()\n    932             +Infinity\n    933         \"\"\"\n--> 934         if not self.is_finite():\n    935             from .infinity import Infinity\n    936             return Infinity\n\n/home/martin/sage-develop/local/lib/python2.7/site-packages/sage/rings/ring.pyx in sage.rings.ring.Ring.is_finite (build/cythonized/sage/rings/ring.c:8953)()\n    915         if self.is_zero():\n    916             return True\n--> 917         return super(Ring, self).is_finite()\n    918 \n    919     def cardinality(self):\n\nAttributeError: 'super' object has no attribute 'is_finite'\n```\n\n**CC:**  @tscrim\n\nIssue created by migration from https://trac.sagemath.org/ticket/26946\n\n",
    "created_at": "2018-12-23T14:49:08Z",
    "labels": [
        "component: algebra",
        "bug",
        "needs work"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-9.8",
    "title": "cardinality of finite multivariate polynomial quotients is broken",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/26946",
    "user": "https://github.com/mantepse"
}
```

```
sage: R.<a> = PolynomialRing(GF(2)); R.quotient((a^2+a)*R).cardinality()
4
sage: R.<a,b> = PolynomialRing(GF(2)); R.quotient((a^2+a, b^2+b)*R).cardinality()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-0d4ecbf62612> in <module>()
----> 1 R = PolynomialRing(GF(Integer(2)), names=('a', 'b',)); (a, b,) = R._first_ngens(2); R.quotient((a**Integer(2)+a, b**Integer(2)+b)*R).cardinality()

/home/martin/sage-develop/local/lib/python2.7/site-packages/sage/rings/ring.pyx in sage.rings.ring.Ring.cardinality (build/cythonized/sage/rings/ring.c:9050)()
    932             +Infinity
    933         """
--> 934         if not self.is_finite():
    935             from .infinity import Infinity
    936             return Infinity

/home/martin/sage-develop/local/lib/python2.7/site-packages/sage/rings/ring.pyx in sage.rings.ring.Ring.is_finite (build/cythonized/sage/rings/ring.c:8953)()
    915         if self.is_zero():
    916             return True
--> 917         return super(Ring, self).is_finite()
    918 
    919     def cardinality(self):

AttributeError: 'super' object has no attribute 'is_finite'
```

**CC:**  @tscrim

Issue created by migration from https://trac.sagemath.org/ticket/26946





---

archive/issue_events_240074.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2019-01-15T18:15:21Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "milestone": "sage-8.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240074"
}
```



---

archive/issue_events_240075.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2019-01-15T18:15:21Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "milestone": "sage-8.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240075"
}
```



---

archive/issue_comments_418154.json:
```json
{
    "body": "<a id='comment:1'></a>\nRetarging tickets optimistically to the next milestone.  If you are responsible for this ticket (either its reporter or owner) and don't believe you are likely to complete this ticket before the next release (8.7) please retarget this ticket's milestone to sage-pending or sage-wishlist.",
    "created_at": "2019-01-15T18:15:21Z",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26946#issuecomment-418154",
    "user": "https://github.com/embray"
}
```

<a id='comment:1'></a>
Retarging tickets optimistically to the next milestone.  If you are responsible for this ticket (either its reporter or owner) and don't believe you are likely to complete this ticket before the next release (8.7) please retarget this ticket's milestone to sage-pending or sage-wishlist.



---

archive/issue_comments_418155.json:
```json
{
    "body": "<a id='comment:2'></a>\nTicket retargeted after milestone closed (if you don't believe this ticket is appropriate for the Sage 8.8 release please retarget manually)",
    "created_at": "2019-03-25T10:56:15Z",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26946#issuecomment-418155",
    "user": "https://github.com/embray"
}
```

<a id='comment:2'></a>
Ticket retargeted after milestone closed (if you don't believe this ticket is appropriate for the Sage 8.8 release please retarget manually)



---

archive/issue_events_240076.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2019-03-25T10:56:15Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "milestone": "sage-8.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240076"
}
```



---

archive/issue_events_240077.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2019-03-25T10:56:15Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "milestone": "sage-8.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240077"
}
```



---

archive/issue_comments_418156.json:
```json
{
    "body": "<a id='comment:3'></a>\nAs the Sage-8.8 release milestone is pending, we should delete the sage-8.8 milestone for tickets that are not actively being worked on or that still require significant work to move forward.  If you feel that this ticket should be included in the next Sage release at the soonest please set its milestone to the next release milestone (sage-8.9).",
    "created_at": "2019-06-14T14:54:19Z",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26946#issuecomment-418156",
    "user": "https://github.com/embray"
}
```

<a id='comment:3'></a>
As the Sage-8.8 release milestone is pending, we should delete the sage-8.8 milestone for tickets that are not actively being worked on or that still require significant work to move forward.  If you feel that this ticket should be included in the next Sage release at the soonest please set its milestone to the next release milestone (sage-8.9).



---

archive/issue_events_240078.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2019-06-14T14:54:19Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "milestone": "sage-8.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240078"
}
```



---

archive/issue_comments_418157.json:
```json
{
    "body": "<a id='comment:4'></a>\nnow returns an error in 9.6.b3 ; so maybe we can close as invalid ?",
    "created_at": "2022-03-06T20:21:14Z",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26946#issuecomment-418157",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:4'></a>
now returns an error in 9.6.b3 ; so maybe we can close as invalid ?



---

archive/issue_events_240079.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2022-03-06T20:21:14Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "label": "invalid",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240079"
}
```



---

archive/issue_events_240080.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2022-03-06T20:21:14Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240080"
}
```



---

archive/issue_events_240081.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2022-03-07T03:29:41Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "milestone": "sage-9.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240081"
}
```



---

archive/issue_comments_418158.json:
```json
{
    "body": "<a id='comment:5'></a>\nI am not sure this should return an error. We can use the `I.vector_space_dimension()` to compute the `cardinality()`, where `I` is the defining ideal. So it would be\n\n```python\ndef cardinality(self):\n    return self.base_ring().cardinality() ** self.defining_ideal().vector_space_dimension()\n```\n\nFor non-fields, this is a harder question that we can raise a `NotImplementedError` for (which means either we catch the `TypeError` from the above or do some other kind of check).\n\nWhat do you think about this? I can do the commit if you agree.\n\nI also noticed the documentation for `vector_space_dimension()` is wrong: it does not raise an error for nonzero dimensional ideals.",
    "created_at": "2022-03-07T03:29:41Z",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26946#issuecomment-418158",
    "user": "https://github.com/tscrim"
}
```

<a id='comment:5'></a>
I am not sure this should return an error. We can use the `I.vector_space_dimension()` to compute the `cardinality()`, where `I` is the defining ideal. So it would be

```python
def cardinality(self):
    return self.base_ring().cardinality() ** self.defining_ideal().vector_space_dimension()
```

For non-fields, this is a harder question that we can raise a `NotImplementedError` for (which means either we catch the `TypeError` from the above or do some other kind of check).

What do you think about this? I can do the commit if you agree.

I also noticed the documentation for `vector_space_dimension()` is wrong: it does not raise an error for nonzero dimensional ideals.



---

archive/issue_events_240082.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2022-03-07T03:29:41Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240082"
}
```



---

archive/issue_events_240083.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2022-03-07T03:29:41Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240083"
}
```



---

archive/issue_events_240084.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-05-03T15:19:01Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "milestone": "sage-9.6",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240084"
}
```



---

archive/issue_events_240085.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-05-03T15:19:01Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "milestone": "sage-9.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240085"
}
```



---

archive/issue_events_240086.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-09-19T18:58:47Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "milestone": "sage-9.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240086"
}
```



---

archive/issue_events_240087.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-09-19T18:58:47Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/26946",
    "milestone": "sage-9.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26946#event-240087"
}
```
