# Issue 34939: Graph with allows_loops = False, has_loops = False and num_edges = 0 returns loop in edge_iterator

archive/issues_034702.json:
```json
{
    "assignees": [],
    "body": "<div id=\"comment:0\"></div>\n\nConsider the following code:\n\n```\nsage: G = Graph()\nsage: G.add_vertex()\n0\nsage: G.allow_loops(True)\nsage: G.add_edge (0, 0)\nsage: G.allow_loops(False, check=False)\nsage: G.allows_loops()\nFalse\nsage: G.has_loops()\nFalse\nsage: G.num_edges()\n0\nsage: list(G.edge_iterator())\n[(0, 0, None)]\n```\n\nThe root of the problem is that using `check=False` in `allow_loops (False, check=False)` does not remove the existing loop(s). I know that it is the goal of this keyword but it should, in case of existing loops, raise an exception (like when one tries to add a loop on a graph where loops are not allowed)\n\n\nBy the way, in my opinion, the name `check` for the keyword argument of `allow_loops` should be rename to something like `delete_existing_loops`.\n\n\n\nEdit: there is a similar situation with multiple edges:\n\n```\nsage: G = Graph()\nsage: G.add_vertices ([0, 1])\nsage: G.add_edge (0, 1)\nsage: G.add_edge (0, 1)\nsage: G.num_edges()\n1\nsage: list(G.edge_iterator())\n[(0, 1, None)]\nsage: G.allow_multiple_edges(True)\nsage: G.add_edge (0, 1, 'label')\nsage: G.num_edges()\n2\nsage: list(G.edge_iterator())\n[(0, 1, None), (0, 1, 'label')]\nsage: \nsage: G.allow_multiple_edges (False, check=False)\nsage: G.allows_multiple_edges()\nFalse\nsage: G.has_multiple_edges()\nFalse\nsage: G.num_edges()\n2\nsage: list(G.edge_iterator()) # only one edge but num_edges = 2 !!\n[(0, 1, None)]\nsage: \nsage: G.allow_multiple_edges(True)\nsage: G.num_edges()\n2\nsage: list(G.edge_iterator())\n[(0, 1, None), (0, 1, 'label')]\n```\n\nComponent: **graph theory**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/34939_\n\n",
    "created_at": "2023-01-26T14:29:16Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20graph%20theory",
        "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
        "https://github.com/sagemath/sage/labels/bug"
    ],
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "Graph with allows_loops = False, has_loops = False and num_edges = 0 returns loop in edge_iterator",
    "type": "issue",
    "updated_at": "2023-01-29T23:06:23Z",
    "url": "https://github.com/sagemath/sage/issues/34939",
    "user": "https://github.com/sagetrac-bouvier"
}
```
<div id="comment:0"></div>

Consider the following code:

```
sage: G = Graph()
sage: G.add_vertex()
0
sage: G.allow_loops(True)
sage: G.add_edge (0, 0)
sage: G.allow_loops(False, check=False)
sage: G.allows_loops()
False
sage: G.has_loops()
False
sage: G.num_edges()
0
sage: list(G.edge_iterator())
[(0, 0, None)]
```

The root of the problem is that using `check=False` in `allow_loops (False, check=False)` does not remove the existing loop(s). I know that it is the goal of this keyword but it should, in case of existing loops, raise an exception (like when one tries to add a loop on a graph where loops are not allowed)


By the way, in my opinion, the name `check` for the keyword argument of `allow_loops` should be rename to something like `delete_existing_loops`.



Edit: there is a similar situation with multiple edges:

```
sage: G = Graph()
sage: G.add_vertices ([0, 1])
sage: G.add_edge (0, 1)
sage: G.add_edge (0, 1)
sage: G.num_edges()
1
sage: list(G.edge_iterator())
[(0, 1, None)]
sage: G.allow_multiple_edges(True)
sage: G.add_edge (0, 1, 'label')
sage: G.num_edges()
2
sage: list(G.edge_iterator())
[(0, 1, None), (0, 1, 'label')]
sage: 
sage: G.allow_multiple_edges (False, check=False)
sage: G.allows_multiple_edges()
False
sage: G.has_multiple_edges()
False
sage: G.num_edges()
2
sage: list(G.edge_iterator()) # only one edge but num_edges = 2 !!
[(0, 1, None)]
sage: 
sage: G.allow_multiple_edges(True)
sage: G.num_edges()
2
sage: list(G.edge_iterator())
[(0, 1, None), (0, 1, 'label')]
```

Component: **graph theory**

_Issue created by migration from https://trac.sagemath.org/ticket/34939_





---

archive/issue_events_473050.json:
```json
{
    "actor": "https://github.com/sagetrac-bouvier",
    "created_at": "2023-01-26T14:29:16Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/34939",
    "milestone_number": null,
    "milestone_title": "sage-9.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34939#event-473050"
}
```



---

archive/issue_events_473051.json:
```json
{
    "actor": "https://github.com/sagetrac-bouvier",
    "created_at": "2023-01-26T14:29:16Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34939",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20graph%20theory",
    "label_color": "0000ff",
    "label_name": "c: graph theory",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34939#event-473051"
}
```



---

archive/issue_events_473052.json:
```json
{
    "actor": "https://github.com/sagetrac-bouvier",
    "created_at": "2023-01-26T14:29:16Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34939",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
    "label_color": "ffbb00",
    "label_name": "p: major / 3",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34939#event-473052"
}
```



---

archive/issue_events_473053.json:
```json
{
    "actor": "https://github.com/sagetrac-bouvier",
    "created_at": "2023-01-26T14:29:16Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34939",
    "label": "https://github.com/sagemath/sage/labels/bug",
    "label_color": "d73a4a",
    "label_name": "bug",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34939#event-473053"
}
```



---

archive/issue_comments_562758.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -17,7 +17,7 @@\n [(0, 0, None)]\n ```\n \n-The root of the problem is that using `check=False` in `allow_loop (False, check=False)` does not remove the existing loop(s). I know that it is the goal of this keyword but it should, in case of existing loops, raise an exception (like when one tries to add a loop on a graph where loops are not allowed)\n+The root of the problem is that using `check=False` in `allow_loops (False, check=False)` does not remove the existing loop(s). I know that it is the goal of this keyword but it should, in case of existing loops, raise an exception (like when one tries to add a loop on a graph where loops are not allowed)\n \n \n By the way, in my opinion, the name `check` for the keyword argument of `allow_loops` should be rename to something like `delete_existing_loops`.\n``````\n",
    "created_at": "2023-01-26T14:30:41Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/34939",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/34939#issuecomment-562758",
    "user": "https://github.com/sagetrac-bouvier"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -17,7 +17,7 @@
 [(0, 0, None)]
 ```
 
-The root of the problem is that using `check=False` in `allow_loop (False, check=False)` does not remove the existing loop(s). I know that it is the goal of this keyword but it should, in case of existing loops, raise an exception (like when one tries to add a loop on a graph where loops are not allowed)
+The root of the problem is that using `check=False` in `allow_loops (False, check=False)` does not remove the existing loop(s). I know that it is the goal of this keyword but it should, in case of existing loops, raise an exception (like when one tries to add a loop on a graph where loops are not allowed)
 
 
 By the way, in my opinion, the name `check` for the keyword argument of `allow_loops` should be rename to something like `delete_existing_loops`.
``````




---

archive/issue_comments_562759.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -21,3 +21,40 @@\n \n \n By the way, in my opinion, the name `check` for the keyword argument of `allow_loops` should be rename to something like `delete_existing_loops`.\n+\n+\n+\n+Edit: there is a similar situation with multiple edges:\n+\n+```\n+sage: G = Graph()\n+sage: G.add_vertices ([0, 1])\n+sage: G.add_edge (0, 1)\n+sage: G.add_edge (0, 1)\n+sage: G.num_edges()\n+1\n+sage: list(G.edge_iterator())\n+[(0, 1, None)]\n+sage: G.allow_multiple_edges(True)\n+sage: G.add_edge (0, 1, 'label')\n+sage: G.num_edges()\n+2\n+sage: list(G.edge_iterator())\n+[(0, 1, None), (0, 1, 'label')]\n+sage: \n+sage: G.allow_multiple_edges (False, check=False)\n+sage: G.allows_multiple_edges()\n+False\n+sage: G.has_multiple_edges()\n+False\n+sage: G.num_edges()\n+2\n+sage: list(G.edge_iterator()) # only one edge but num_edges = 2 !!\n+[(0, 1, None)]\n+sage: \n+sage: G.allow_multiple_edges(True)\n+sage: G.num_edges()\n+2\n+sage: list(G.edge_iterator())\n+[(0, 1, None), (0, 1, 'label')]\n+```\n``````\n",
    "created_at": "2023-01-26T14:37:31Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/34939",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/34939#issuecomment-562759",
    "user": "https://github.com/sagetrac-bouvier"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -21,3 +21,40 @@
 
 
 By the way, in my opinion, the name `check` for the keyword argument of `allow_loops` should be rename to something like `delete_existing_loops`.
+
+
+
+Edit: there is a similar situation with multiple edges:
+
+```
+sage: G = Graph()
+sage: G.add_vertices ([0, 1])
+sage: G.add_edge (0, 1)
+sage: G.add_edge (0, 1)
+sage: G.num_edges()
+1
+sage: list(G.edge_iterator())
+[(0, 1, None)]
+sage: G.allow_multiple_edges(True)
+sage: G.add_edge (0, 1, 'label')
+sage: G.num_edges()
+2
+sage: list(G.edge_iterator())
+[(0, 1, None), (0, 1, 'label')]
+sage: 
+sage: G.allow_multiple_edges (False, check=False)
+sage: G.allows_multiple_edges()
+False
+sage: G.has_multiple_edges()
+False
+sage: G.num_edges()
+2
+sage: list(G.edge_iterator()) # only one edge but num_edges = 2 !!
+[(0, 1, None)]
+sage: 
+sage: G.allow_multiple_edges(True)
+sage: G.num_edges()
+2
+sage: list(G.edge_iterator())
+[(0, 1, None), (0, 1, 'label')]
+```
``````




---

archive/issue_events_473054.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2023-01-29T23:06:23Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/34939",
    "milestone_number": null,
    "milestone_title": "sage-9.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34939#event-473054"
}
```
