# Issue 29463: homebrew-macos-standard: Fix Fortran-related doctest errors

archive/issues_029226.json:
```json
{
    "assignees": [],
    "body": "<div id=\"comment:0\"></div>\n\nFrom #29451:\n\nhttps://github.com/mkoeppe/sage/runs/559191935\n\n```\n----------------------------------------------------------------------\nsage -t src/sage/interfaces/gap.py  # 1 doctest failed\nsage -t src/sage/misc/inline_fortran.py  # 3 doctests failed\nsage -t src/sage/misc/persist.pyx  # 2 doctests failed\nsage -t src/sage/repl/ipython_extension.py  # 4 doctests failed\n----------------------------------------------------------------------\n```\n\n```\n      File \"/Users/runner/runners/2.165.2/work/sage/sage/.tox/local-homebrew-macos-standard/local/lib/python3.7/site-packages/sage/misc/inline_fortran.py\", line 194, in eval\n        \"failed to compile Fortran code:\\n{}\".format(exc.output))\n    RuntimeError: failed to compile Fortran code:\n    b'Could not locate executable g++ -std=gnu++11 -pthread -bundle -undefined dynamic_lookup\\nIn file included from /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpjff9tknw/src.macosx-10.15-x86_64-3.7/fortran_modulemodule.c:16:\\nIn file included from /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpjff9tknw/src.macosx-10.15-x86_64-3.7/fortranobject.h:13:\\nIn file included from \n```\n\nTo reproduce (with #29417):\n\n```\n tox -e local-homebrew-macos-standard -- ptest \n```\n\n\nCC:  @jhpalmieri @isuruf @dimpase\n\nComponent: **porting**\n\nReviewer: **John Palmieri**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/29463_\n\n",
    "closed_at": "2020-05-06T16:50:00Z",
    "created_at": "2020-04-04T13:27:40Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/bug",
        "https://github.com/sagemath/sage/labels/c%3A%20porting",
        "https://github.com/sagemath/sage/labels/duplicate"
    ],
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "homebrew-macos-standard: Fix Fortran-related doctest errors",
    "type": "issue",
    "updated_at": "2020-05-06T16:50:00Z",
    "url": "https://github.com/sagemath/sage/issues/29463",
    "user": "https://github.com/mkoeppe"
}
```
<div id="comment:0"></div>

From #29451:

https://github.com/mkoeppe/sage/runs/559191935

```
----------------------------------------------------------------------
sage -t src/sage/interfaces/gap.py  # 1 doctest failed
sage -t src/sage/misc/inline_fortran.py  # 3 doctests failed
sage -t src/sage/misc/persist.pyx  # 2 doctests failed
sage -t src/sage/repl/ipython_extension.py  # 4 doctests failed
----------------------------------------------------------------------
```

```
      File "/Users/runner/runners/2.165.2/work/sage/sage/.tox/local-homebrew-macos-standard/local/lib/python3.7/site-packages/sage/misc/inline_fortran.py", line 194, in eval
        "failed to compile Fortran code:\n{}".format(exc.output))
    RuntimeError: failed to compile Fortran code:
    b'Could not locate executable g++ -std=gnu++11 -pthread -bundle -undefined dynamic_lookup\nIn file included from /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpjff9tknw/src.macosx-10.15-x86_64-3.7/fortran_modulemodule.c:16:\nIn file included from /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpjff9tknw/src.macosx-10.15-x86_64-3.7/fortranobject.h:13:\nIn file included from 
```

To reproduce (with #29417):

```
 tox -e local-homebrew-macos-standard -- ptest 
```


CC:  @jhpalmieri @isuruf @dimpase

Component: **porting**

Reviewer: **John Palmieri**

_Issue created by migration from https://trac.sagemath.org/ticket/29463_





---

archive/issue_events_402660.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-04-04T13:27:40Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "milestone_number": null,
    "milestone_title": "sage-9.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402660"
}
```



---

archive/issue_events_402661.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-04-04T13:27:40Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20porting",
    "label_color": "0000b0",
    "label_name": "c: porting",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402661"
}
```



---

archive/issue_events_402662.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-04-04T13:27:40Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20critical%20/%202",
    "label_color": "ff7700",
    "label_name": "p: critical / 2",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402662"
}
```



---

archive/issue_events_402663.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-04-04T13:27:40Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "label": "https://github.com/sagemath/sage/labels/bug",
    "label_color": "d73a4a",
    "label_name": "bug",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402663"
}
```



---

archive/issue_comments_463153.json:
```json
{
    "body": "<div id=\"comment:1\" align=\"right\">comment:1</div>\n\nShould check if the fix in #29408 fixes any of these too.",
    "created_at": "2020-04-09T03:59:28Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29463#issuecomment-463153",
    "user": "https://github.com/mkoeppe"
}
```

<div id="comment:1" align="right">comment:1</div>

Should check if the fix in #29408 fixes any of these too.



---

archive/issue_comments_463154.json:
```json
{
    "body": "<div id=\"comment:2\" align=\"right\">comment:2</div>\n\nTests at https://github.com/mkoeppe/sage/actions/runs/73955490",
    "created_at": "2020-04-09T03:59:40Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29463#issuecomment-463154",
    "user": "https://github.com/mkoeppe"
}
```

<div id="comment:2" align="right">comment:2</div>

Tests at https://github.com/mkoeppe/sage/actions/runs/73955490



---

archive/issue_comments_463155.json:
```json
{
    "body": "<div id=\"comment:3\" align=\"right\">comment:3</div>\n\nThe fix in #29408 works at least with the OS X Python installation. When I say \"works,\" I mean that all tests pass. I did, however, twice see a dialog box saying \"Python quit unexpectedly.\"\n\nI will also try with Homebrew's Python.",
    "created_at": "2020-04-09T19:00:19Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29463#issuecomment-463155",
    "user": "https://github.com/jhpalmieri"
}
```

<div id="comment:3" align="right">comment:3</div>

The fix in #29408 works at least with the OS X Python installation. When I say "works," I mean that all tests pass. I did, however, twice see a dialog box saying "Python quit unexpectedly."

I will also try with Homebrew's Python.



---

archive/issue_comments_463156.json:
```json
{
    "body": "<div id=\"comment:4\" align=\"right\">comment:4</div>\n\nSame behavior with Homebrew's Python. So if #29408 gets a positive review, we can close this.",
    "created_at": "2020-04-09T23:28:09Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29463#issuecomment-463156",
    "user": "https://github.com/jhpalmieri"
}
```

<div id="comment:4" align="right">comment:4</div>

Same behavior with Homebrew's Python. So if #29408 gets a positive review, we can close this.



---

archive/issue_comments_463157.json:
```json
{
    "body": "<div id=\"comment:5\" align=\"right\">comment:5</div>\n\nReplying to [@jhpalmieri](#comment%3A3):\n> The fix in #29408 works at least with the OS X Python installation. When I say \"works,\" I mean that all tests pass. I did, however, twice see a dialog box saying \"Python quit unexpectedly.\"\n\nYes, I have seen this too on my machine.  My guess is that we have some tests that crash some python process deliberately",
    "created_at": "2020-04-09T23:37:58Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29463#issuecomment-463157",
    "user": "https://github.com/mkoeppe"
}
```

<div id="comment:5" align="right">comment:5</div>

Replying to [@jhpalmieri](#comment%3A3):
> The fix in #29408 works at least with the OS X Python installation. When I say "works," I mean that all tests pass. I did, however, twice see a dialog box saying "Python quit unexpectedly."

Yes, I have seen this too on my machine.  My guess is that we have some tests that crash some python process deliberately



---

archive/issue_comments_463158.json:
```json
{
    "body": "<div id=\"comment:6\" align=\"right\">comment:6</div>\n\nOh, yes, that makes sense.",
    "created_at": "2020-04-10T00:08:35Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29463#issuecomment-463158",
    "user": "https://github.com/jhpalmieri"
}
```

<div id="comment:6" align="right">comment:6</div>

Oh, yes, that makes sense.



---

archive/issue_events_402664.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-04-15T03:24:46Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20critical%20/%202",
    "label_color": "ff7700",
    "label_name": "p: critical / 2",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402664"
}
```



---

archive/issue_events_402665.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-04-15T03:24:46Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20blocker%20/%201",
    "label_color": "ff0000",
    "label_name": "p: blocker / 1",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402665"
}
```



---

archive/issue_comments_463159.json:
```json
{
    "body": "<div id=\"comment:8\" align=\"right\">comment:8</div>\n\nStill present on 9.1.rc0 because #29408 is not merged",
    "created_at": "2020-04-15T19:43:47Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29463#issuecomment-463159",
    "user": "https://github.com/mkoeppe"
}
```

<div id="comment:8" align="right">comment:8</div>

Still present on 9.1.rc0 because #29408 is not merged



---

archive/issue_comments_463160.json:
```json
{
    "body": "<div id=\"comment:9\" align=\"right\">comment:9</div>\n\nCan now be closed, I think.",
    "created_at": "2020-04-18T21:57:18Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29463#issuecomment-463160",
    "user": "https://github.com/jhpalmieri"
}
```

<div id="comment:9" align="right">comment:9</div>

Can now be closed, I think.



---

archive/issue_events_402666.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-04-18T22:51:30Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402666"
}
```



---

archive/issue_events_402667.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-04-18T22:51:30Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "milestone_number": null,
    "milestone_title": "sage-9.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402667"
}
```



---

archive/issue_events_402668.json:
```json
{
    "actor": "https://github.com/jhpalmieri",
    "created_at": "2020-04-18T23:39:46Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402668"
}
```



---

archive/issue_events_402669.json:
```json
{
    "actor": "https://github.com/jhpalmieri",
    "created_at": "2020-04-18T23:39:46Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402669"
}
```



---

archive/issue_comments_463161.json:
```json
{
    "body": "Reviewer: **John Palmieri**",
    "created_at": "2020-04-18T23:39:46Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29463#issuecomment-463161",
    "user": "https://github.com/jhpalmieri"
}
```

Reviewer: **John Palmieri**



---

archive/issue_events_402670.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-05-06T16:50:00Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402670"
}
```



---

archive/issue_events_402671.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-05-06T16:50:00Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402671"
}
```



---

archive/issue_events_402672.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-05-06T16:50:00Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20blocker%20/%201",
    "label_color": "ff0000",
    "label_name": "p: blocker / 1",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402672"
}
```



---

archive/issue_events_402673.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-05-06T16:50:00Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29463",
    "label": "https://github.com/sagemath/sage/labels/duplicate",
    "label_color": "c6c6c6",
    "label_name": "duplicate",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29463#event-402673"
}
```
