# Issue 29851: tox.ini: debian-bullseye, -sid have Python3.8 instead of 3.7

archive/issues_029614.json:
```json
{
    "body": "As per the wiki, running \n\n```\n\nbuild/bin/write-dockerfile.sh debian \"@(standard|optional)\" > Dockerfile\n```\n\n\nGenerates a Dockerfile, but running the dockerfile fails because Debian (at least) comes with Python3.8, not 3.7. This can be fixed by changing the file build/pkgs/python3/distros/debian.txt, but I don't know if that will have unexpected consequences.\n\n**CC:**  @dimpase @kliem\n\n**Branch/Commit:** [1e7becc551c3bad53ce67fa8457c5c3d977cad71](https://github.com/sagemath/sagetrac-mirror/commit/1e7becc551c3bad53ce67fa8457c5c3d977cad71)\n\n**Reviewer:** Jonathan Kliem\n\n**Author:** Matthias Koeppe\n\nIssue created by migration from https://trac.sagemath.org/ticket/29851\n\n",
    "closed_at": "2020-07-08T19:32:22Z",
    "created_at": "2020-06-12T21:09:08Z",
    "labels": [
        "component: porting",
        "minor",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-9.2",
    "title": "tox.ini: debian-bullseye, -sid have Python3.8 instead of 3.7",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/29851",
    "user": "https://github.com/cduston44"
}
```
As per the wiki, running 

```

build/bin/write-dockerfile.sh debian "@(standard|optional)" > Dockerfile
```


Generates a Dockerfile, but running the dockerfile fails because Debian (at least) comes with Python3.8, not 3.7. This can be fixed by changing the file build/pkgs/python3/distros/debian.txt, but I don't know if that will have unexpected consequences.

**CC:**  @dimpase @kliem

**Branch/Commit:** [1e7becc551c3bad53ce67fa8457c5c3d977cad71](https://github.com/sagemath/sagetrac-mirror/commit/1e7becc551c3bad53ce67fa8457c5c3d977cad71)

**Reviewer:** Jonathan Kliem

**Author:** Matthias Koeppe

Issue created by migration from https://trac.sagemath.org/ticket/29851





---

archive/issue_comments_474330.json:
```json
{
    "body": "<a id='comment:1'></a>\nYes, this will have to be changed when we support Python 3.8 (#27754). At the moment, we only accept Python 3.7.x in `configure`; ticket #29033 adds Python 3.6.x support.",
    "created_at": "2020-06-12T21:56:10Z",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29851#issuecomment-474330",
    "user": "https://github.com/mkoeppe"
}
```

<a id='comment:1'></a>
Yes, this will have to be changed when we support Python 3.8 (#27754). At the moment, we only accept Python 3.7.x in `configure`; ticket #29033 adds Python 3.6.x support.



---

archive/issue_comments_474331.json:
```json
{
    "body": "<a id='comment:2'></a>\nAlso, see the flag IGNORE_MISSING_SYSTEM_PACKAGES in tox.ini, which we use both for too old versions of the distribution that don't have all packages, and for too new versions of the distribution, such as `ubuntu-focal`.",
    "created_at": "2020-06-12T21:58:48Z",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29851#issuecomment-474331",
    "user": "https://github.com/mkoeppe"
}
```

<a id='comment:2'></a>
Also, see the flag IGNORE_MISSING_SYSTEM_PACKAGES in tox.ini, which we use both for too old versions of the distribution that don't have all packages, and for too new versions of the distribution, such as `ubuntu-focal`.



---

archive/issue_events_268649.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-06-12T22:09:19Z",
    "event": "renamed",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "rename": {
        "from": "write-dockerfile.sh: Debian has Python3.8 instead of 3.7",
        "to": "tox.ini: debian-bullseye, -sid have Python3.8 instead of 3.7"
    },
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29851#event-268649"
}
```



---

archive/issue_comments_474332.json:
```json
{
    "body": "**Branch:** [u/mkoeppe/tox_ini__debian_bullseye___sid_have_python3_8_instead_of_3_7](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/tox_ini__debian_bullseye___sid_have_python3_8_instead_of_3_7)",
    "created_at": "2020-06-14T01:17:44Z",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29851#issuecomment-474332",
    "user": "https://github.com/mkoeppe"
}
```

**Branch:** [u/mkoeppe/tox_ini__debian_bullseye___sid_have_python3_8_instead_of_3_7](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/tox_ini__debian_bullseye___sid_have_python3_8_instead_of_3_7)



---

archive/issue_comments_474333.json:
```json
{
    "body": "**Commit:** [1e7becc551c3bad53ce67fa8457c5c3d977cad71](https://github.com/sagemath/sagetrac-mirror/commit/1e7becc551c3bad53ce67fa8457c5c3d977cad71)",
    "created_at": "2020-06-14T01:18:05Z",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29851#issuecomment-474333",
    "user": "https://github.com/mkoeppe"
}
```

**Commit:** [1e7becc551c3bad53ce67fa8457c5c3d977cad71](https://github.com/sagemath/sagetrac-mirror/commit/1e7becc551c3bad53ce67fa8457c5c3d977cad71)



---

archive/issue_comments_474334.json:
```json
{
    "body": "<a id='comment:5'></a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/1e7becc551c3bad53ce67fa8457c5c3d977cad71\">1e7becc</a></td><td><code>tox.ini [debian-buster, -sid]: IGNORE_MISSING_SYSTEM_PACKAGES=yes because of libpython3.7-dev</code></td></tr></table>\n",
    "created_at": "2020-06-14T01:18:05Z",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29851#issuecomment-474334",
    "user": "https://github.com/mkoeppe"
}
```

<a id='comment:5'></a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/1e7becc551c3bad53ce67fa8457c5c3d977cad71">1e7becc</a></td><td><code>tox.ini [debian-buster, -sid]: IGNORE_MISSING_SYSTEM_PACKAGES=yes because of libpython3.7-dev</code></td></tr></table>




---

archive/issue_events_268650.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-06-14T01:18:05Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29851#event-268650"
}
```



---

archive/issue_comments_474335.json:
```json
{
    "body": "**Author:** Matthias Koeppe",
    "created_at": "2020-06-14T01:18:05Z",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29851#issuecomment-474335",
    "user": "https://github.com/mkoeppe"
}
```

**Author:** Matthias Koeppe



---

archive/issue_comments_474336.json:
```json
{
    "body": "**Reviewer:** Jonathan Kliem",
    "created_at": "2020-06-18T19:04:50Z",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29851#issuecomment-474336",
    "user": "https://github.com/kliem"
}
```

**Reviewer:** Jonathan Kliem



---

archive/issue_comments_474337.json:
```json
{
    "body": "<a id='comment:7'></a>\nI already noticed the problem. So what this does it just make the workflow go through, even though it coulnd't install python3.7. It will later find out that no suitable python can be found and install python3.7 for sage.",
    "created_at": "2020-06-18T19:04:50Z",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29851#issuecomment-474337",
    "user": "https://github.com/kliem"
}
```

<a id='comment:7'></a>
I already noticed the problem. So what this does it just make the workflow go through, even though it coulnd't install python3.7. It will later find out that no suitable python can be found and install python3.7 for sage.



---

archive/issue_comments_474338.json:
```json
{
    "body": "<a id='comment:8'></a>\nThat's right. Best we can do before we get to Python 3.8 compatibility in #27754, which seems to have stalled",
    "created_at": "2020-06-19T00:55:37Z",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29851#issuecomment-474338",
    "user": "https://github.com/mkoeppe"
}
```

<a id='comment:8'></a>
That's right. Best we can do before we get to Python 3.8 compatibility in #27754, which seems to have stalled



---

archive/issue_events_268651.json:
```json
{
    "actor": "https://github.com/kliem",
    "created_at": "2020-06-19T06:01:11Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29851#event-268651"
}
```



---

archive/issue_events_268652.json:
```json
{
    "actor": "https://github.com/kliem",
    "created_at": "2020-06-19T06:01:11Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29851#event-268652"
}
```



---

archive/issue_comments_474339.json:
```json
{
    "body": "<a id='comment:10'></a>\nThanks!",
    "created_at": "2020-06-19T15:02:37Z",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29851#issuecomment-474339",
    "user": "https://github.com/mkoeppe"
}
```

<a id='comment:10'></a>
Thanks!



---

archive/issue_comments_474340.json:
```json
{
    "body": "**Changing branch** from \"[u/mkoeppe/tox_ini__debian_bullseye___sid_have_python3_8_instead_of_3_7](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/tox_ini__debian_bullseye___sid_have_python3_8_instead_of_3_7)\" to \"[1e7becc551c3bad53ce67fa8457c5c3d977cad71](https://github.com/sagemath/sagetrac-mirror/commit/1e7becc551c3bad53ce67fa8457c5c3d977cad71)\".",
    "created_at": "2020-07-08T19:32:22Z",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/29851#issuecomment-474340",
    "user": "https://github.com/vbraun"
}
```

**Changing branch** from "[u/mkoeppe/tox_ini__debian_bullseye___sid_have_python3_8_instead_of_3_7](https://github.com/sagemath/sagetrac-mirror/tree/u/mkoeppe/tox_ini__debian_bullseye___sid_have_python3_8_instead_of_3_7)" to "[1e7becc551c3bad53ce67fa8457c5c3d977cad71](https://github.com/sagemath/sagetrac-mirror/commit/1e7becc551c3bad53ce67fa8457c5c3d977cad71)".



---

archive/issue_events_268653.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2020-07-08T19:32:22Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29851#event-268653"
}
```



---

archive/issue_events_268654.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "ad109e36493c18eb2989c1b358956bf7f06bb9ed",
    "created_at": "2020-07-08T19:32:22Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/29851",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/29851#event-268654"
}
```
