# Issue 19132: Start a single process when running Sage

archive/issues_018895.json:
```json
{
    "body": "Jupyter assumes that it is running a single process, otherwise interrupts get sent to the wrong process. With Sage, this assumption is currently not true due to the \"front-end\" `$SAGE_ROOT/sage` script. If we instead use `exec` there and apply #19135, this is no longer a problem and Sage Jupyter notebooks can be interrupted properly.\n\n**Branch/Commit:** [a281e344e30955987df1d696b25b18f452c5a218](https://github.com/sagemath/sagetrac-mirror/commit/a281e344e30955987df1d696b25b18f452c5a218)\n\n**Reviewer:** Travis Scrimshaw\n\n**Author:** Jeroen Demeyer\n\nIssue created by migration from https://trac.sagemath.org/ticket/19132\n\n",
    "closed_at": "2015-09-17T09:24:11Z",
    "created_at": "2015-09-04T12:40:30Z",
    "labels": [
        "component: interfaces",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-6.9",
    "title": "Start a single process when running Sage",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/19132",
    "user": "https://github.com/jdemeyer"
}
```
Jupyter assumes that it is running a single process, otherwise interrupts get sent to the wrong process. With Sage, this assumption is currently not true due to the "front-end" `$SAGE_ROOT/sage` script. If we instead use `exec` there and apply #19135, this is no longer a problem and Sage Jupyter notebooks can be interrupted properly.

**Branch/Commit:** [a281e344e30955987df1d696b25b18f452c5a218](https://github.com/sagemath/sagetrac-mirror/commit/a281e344e30955987df1d696b25b18f452c5a218)

**Reviewer:** Travis Scrimshaw

**Author:** Jeroen Demeyer

Issue created by migration from https://trac.sagemath.org/ticket/19132





---

archive/issue_comments_272980.json:
```json
{
    "body": "**Branch:** [u/jdemeyer/fix_interrupts_in_jupyter](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/fix_interrupts_in_jupyter)",
    "created_at": "2015-09-04T14:11:10Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272980",
    "user": "https://github.com/jdemeyer"
}
```

**Branch:** [u/jdemeyer/fix_interrupts_in_jupyter](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/fix_interrupts_in_jupyter)



---

archive/issue_comments_272981.json:
```json
{
    "body": "<a id='comment:2'></a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/af48d8b6c3c9f9e6de65628ff7fdd77ec89b2fb3\">af48d8b</a></td><td><code>Fix interrupts in Jupyter</code></td></tr></table>\n",
    "created_at": "2015-09-04T14:31:29Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272981",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:2'></a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/af48d8b6c3c9f9e6de65628ff7fdd77ec89b2fb3">af48d8b</a></td><td><code>Fix interrupts in Jupyter</code></td></tr></table>




---

archive/issue_comments_272982.json:
```json
{
    "body": "**Upstream:** Reported upstream. No feedback yet.",
    "created_at": "2015-09-04T14:31:29Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272982",
    "user": "https://github.com/jdemeyer"
}
```

**Upstream:** Reported upstream. No feedback yet.



---

archive/issue_comments_272983.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -4,3 +4,7 @@\n factor(2^1000 + 1)\n ```\n cannot be interrupted for example.\n+\n+Upstream tickets:\n+* [https://github.com/ipython/ipykernel/pull/49](https://github.com/ipython/ipykernel/pull/49)\n+* [https://github.com/jupyter/jupyter_client/pull/68](https://github.com/jupyter/jupyter_client/pull/68)\n``````\n",
    "created_at": "2015-09-04T14:31:29Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272983",
    "user": "https://github.com/jdemeyer"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -4,3 +4,7 @@
 factor(2^1000 + 1)
 ```
 cannot be interrupted for example.
+
+Upstream tickets:
+* [https://github.com/ipython/ipykernel/pull/49](https://github.com/ipython/ipykernel/pull/49)
+* [https://github.com/jupyter/jupyter_client/pull/68](https://github.com/jupyter/jupyter_client/pull/68)
``````




---

archive/issue_comments_272984.json:
```json
{
    "body": "**Commit:** [af48d8b6c3c9f9e6de65628ff7fdd77ec89b2fb3](https://github.com/sagemath/sagetrac-mirror/commit/af48d8b6c3c9f9e6de65628ff7fdd77ec89b2fb3)",
    "created_at": "2015-09-04T14:31:29Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272984",
    "user": "https://github.com/jdemeyer"
}
```

**Commit:** [af48d8b6c3c9f9e6de65628ff7fdd77ec89b2fb3](https://github.com/sagemath/sagetrac-mirror/commit/af48d8b6c3c9f9e6de65628ff7fdd77ec89b2fb3)



---

archive/issue_events_173674.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2015-09-04T14:32:27Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/19132#event-173674"
}
```



---

archive/issue_comments_272985.json:
```json
{
    "body": "**Changing upstream** from \"Reported upstream. No feedback yet.\" to \"None of the above - read trac for reasoning.\".",
    "created_at": "2015-09-04T21:09:20Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272985",
    "user": "https://github.com/jdemeyer"
}
```

**Changing upstream** from "Reported upstream. No feedback yet." to "None of the above - read trac for reasoning.".



---

archive/issue_comments_272986.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -6,5 +6,5 @@\n cannot be interrupted for example.\n \n Upstream tickets:\n-* [https://github.com/ipython/ipykernel/pull/49](https://github.com/ipython/ipykernel/pull/49)\n-* [https://github.com/jupyter/jupyter_client/pull/68](https://github.com/jupyter/jupyter_client/pull/68)\n+* [https://github.com/ipython/ipykernel/pull/49](https://github.com/ipython/ipykernel/pull/49) (merged upstream)\n+* [https://github.com/jupyter/jupyter_client/pull/68](https://github.com/jupyter/jupyter_client/pull/68) (no feedback yet)\n``````\n",
    "created_at": "2015-09-04T21:09:20Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272986",
    "user": "https://github.com/jdemeyer"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -6,5 +6,5 @@
 cannot be interrupted for example.
 
 Upstream tickets:
-* [https://github.com/ipython/ipykernel/pull/49](https://github.com/ipython/ipykernel/pull/49)
-* [https://github.com/jupyter/jupyter_client/pull/68](https://github.com/jupyter/jupyter_client/pull/68)
+* [https://github.com/ipython/ipykernel/pull/49](https://github.com/ipython/ipykernel/pull/49) (merged upstream)
+* [https://github.com/jupyter/jupyter_client/pull/68](https://github.com/jupyter/jupyter_client/pull/68) (no feedback yet)
``````




---

archive/issue_events_173675.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2015-09-07T09:42:55Z",
    "event": "renamed",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "rename": {
        "from": "Fix interrupts in Jupyter",
        "to": "Start a single process when running Sage"
    },
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/19132#event-173675"
}
```



---

archive/issue_events_173676.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2015-09-07T09:42:55Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/19132#event-173676"
}
```



---

archive/issue_events_173677.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2015-09-07T09:42:55Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/19132#event-173677"
}
```



---

archive/issue_comments_272987.json:
```json
{
    "body": "**Changing upstream** from \"None of the above - read trac for reasoning.\" to \"\".",
    "created_at": "2015-09-07T09:42:55Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272987",
    "user": "https://github.com/jdemeyer"
}
```

**Changing upstream** from "None of the above - read trac for reasoning." to "".



---

archive/issue_comments_272988.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -1,10 +1 @@\n-Jupyter messes with Sage's interrupt (`SIGINT`) handler, such that code like\n-\n-```\n-factor(2^1000 + 1)\n-```\n-cannot be interrupted for example.\n-\n-Upstream tickets:\n-* [https://github.com/ipython/ipykernel/pull/49](https://github.com/ipython/ipykernel/pull/49) (merged upstream)\n-* [https://github.com/jupyter/jupyter_client/pull/68](https://github.com/jupyter/jupyter_client/pull/68) (no feedback yet)\n+Jupyter assumes that it is running a single process. With Sage, this assumption is currently not true due to the \"front-end\" `$SAGE_ROOT/sage` script. If we instead use `exec` there, this is no longer a problem.\n``````\n",
    "created_at": "2015-09-07T09:42:55Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272988",
    "user": "https://github.com/jdemeyer"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -1,10 +1 @@
-Jupyter messes with Sage's interrupt (`SIGINT`) handler, such that code like
-
-```
-factor(2^1000 + 1)
-```
-cannot be interrupted for example.
-
-Upstream tickets:
-* [https://github.com/ipython/ipykernel/pull/49](https://github.com/ipython/ipykernel/pull/49) (merged upstream)
-* [https://github.com/jupyter/jupyter_client/pull/68](https://github.com/jupyter/jupyter_client/pull/68) (no feedback yet)
+Jupyter assumes that it is running a single process. With Sage, this assumption is currently not true due to the "front-end" `$SAGE_ROOT/sage` script. If we instead use `exec` there, this is no longer a problem.
``````




---

archive/issue_comments_272989.json:
```json
{
    "body": "<a id='comment:6'></a>\n**Branch pushed to git repo; I updated commit sha1. This was a forced push.** **New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/a281e344e30955987df1d696b25b18f452c5a218\">a281e34</a></td><td><code>Start a single process when running Sage</code></td></tr></table>\n",
    "created_at": "2015-09-07T09:46:50Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272989",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

<a id='comment:6'></a>
**Branch pushed to git repo; I updated commit sha1. This was a forced push.** **New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/a281e344e30955987df1d696b25b18f452c5a218">a281e34</a></td><td><code>Start a single process when running Sage</code></td></tr></table>




---

archive/issue_comments_272990.json:
```json
{
    "body": "**Changing commit** from \"[af48d8b6c3c9f9e6de65628ff7fdd77ec89b2fb3](https://github.com/sagemath/sagetrac-mirror/commit/af48d8b6c3c9f9e6de65628ff7fdd77ec89b2fb3)\" to \"[a281e344e30955987df1d696b25b18f452c5a218](https://github.com/sagemath/sagetrac-mirror/commit/a281e344e30955987df1d696b25b18f452c5a218)\".",
    "created_at": "2015-09-07T09:46:50Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272990",
    "user": "https://trac.sagemath.org/admin/accounts/users/git"
}
```

**Changing commit** from "[af48d8b6c3c9f9e6de65628ff7fdd77ec89b2fb3](https://github.com/sagemath/sagetrac-mirror/commit/af48d8b6c3c9f9e6de65628ff7fdd77ec89b2fb3)" to "[a281e344e30955987df1d696b25b18f452c5a218](https://github.com/sagemath/sagetrac-mirror/commit/a281e344e30955987df1d696b25b18f452c5a218)".



---

archive/issue_comments_272991.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -1 +1 @@\n-Jupyter assumes that it is running a single process. With Sage, this assumption is currently not true due to the \"front-end\" `$SAGE_ROOT/sage` script. If we instead use `exec` there, this is no longer a problem.\n+Jupyter assumes that it is running a single process. With Sage, this assumption is currently not true due to the \"front-end\" `$SAGE_ROOT/sage` script. If we instead use `exec` there and apply #19135, this is no longer a problem.\n``````\n",
    "created_at": "2015-09-07T09:47:16Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272991",
    "user": "https://github.com/jdemeyer"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -1 +1 @@
-Jupyter assumes that it is running a single process. With Sage, this assumption is currently not true due to the "front-end" `$SAGE_ROOT/sage` script. If we instead use `exec` there, this is no longer a problem.
+Jupyter assumes that it is running a single process. With Sage, this assumption is currently not true due to the "front-end" `$SAGE_ROOT/sage` script. If we instead use `exec` there and apply #19135, this is no longer a problem.
``````




---

archive/issue_events_173678.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2015-09-07T09:47:16Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/19132#event-173678"
}
```



---

archive/issue_events_173679.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2015-09-07T09:47:16Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/19132#event-173679"
}
```



---

archive/issue_comments_272992.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -1 +1 @@\n-Jupyter assumes that it is running a single process. With Sage, this assumption is currently not true due to the \"front-end\" `$SAGE_ROOT/sage` script. If we instead use `exec` there and apply #19135, this is no longer a problem.\n+Jupyter assumes that it is running a single process, otherwise interrupts get sent to the wrong process. With Sage, this assumption is currently not true due to the \"front-end\" `$SAGE_ROOT/sage` script. If we instead use `exec` there and apply #19135, this is no longer a problem and Sage Jupyter notebooks can be interrupted properly.\n``````\n",
    "created_at": "2015-09-07T20:09:45Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272992",
    "user": "https://github.com/jdemeyer"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -1 +1 @@
-Jupyter assumes that it is running a single process. With Sage, this assumption is currently not true due to the "front-end" `$SAGE_ROOT/sage` script. If we instead use `exec` there and apply #19135, this is no longer a problem.
+Jupyter assumes that it is running a single process, otherwise interrupts get sent to the wrong process. With Sage, this assumption is currently not true due to the "front-end" `$SAGE_ROOT/sage` script. If we instead use `exec` there and apply #19135, this is no longer a problem and Sage Jupyter notebooks can be interrupted properly.
``````




---

archive/issue_events_173680.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2015-09-15T23:42:30Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/19132#event-173680"
}
```



---

archive/issue_events_173681.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2015-09-15T23:42:30Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/19132#event-173681"
}
```



---

archive/issue_comments_272993.json:
```json
{
    "body": "**Reviewer:** Travis Scrimshaw",
    "created_at": "2015-09-15T23:42:30Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272993",
    "user": "https://github.com/tscrim"
}
```

**Reviewer:** Travis Scrimshaw



---

archive/issue_comments_272994.json:
```json
{
    "body": "<a id='comment:9'></a>\nLGTM; we don't need the extra process from the shell running around.",
    "created_at": "2015-09-15T23:42:30Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272994",
    "user": "https://github.com/tscrim"
}
```

<a id='comment:9'></a>
LGTM; we don't need the extra process from the shell running around.



---

archive/issue_events_173682.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2015-09-17T09:24:11Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/19132#event-173682"
}
```



---

archive/issue_events_173683.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "52f4c0377b2bd993104073c6b7ab7b274e5648ad",
    "created_at": "2015-09-17T09:24:11Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/19132#event-173683"
}
```



---

archive/issue_comments_272995.json:
```json
{
    "body": "**Changing branch** from \"[u/jdemeyer/fix_interrupts_in_jupyter](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/fix_interrupts_in_jupyter)\" to \"[a281e344e30955987df1d696b25b18f452c5a218](https://github.com/sagemath/sagetrac-mirror/commit/a281e344e30955987df1d696b25b18f452c5a218)\".",
    "created_at": "2015-09-17T09:24:11Z",
    "issue": "https://github.com/sagemath/sage/issues/19132",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/19132#issuecomment-272995",
    "user": "https://github.com/vbraun"
}
```

**Changing branch** from "[u/jdemeyer/fix_interrupts_in_jupyter](https://github.com/sagemath/sagetrac-mirror/tree/u/jdemeyer/fix_interrupts_in_jupyter)" to "[a281e344e30955987df1d696b25b18f452c5a218](https://github.com/sagemath/sagetrac-mirror/commit/a281e344e30955987df1d696b25b18f452c5a218)".
