# Issue 14079: Cython interface to pselect() system call

archive/issues_013875.json:
```json
{
    "body": "Useful for the new doctesting framework.\n\nDepends on #14080\n\nDepends on #12415\n\n**Assignee:** @jasongrout\n\n**Reviewer:** Volker Braun\n\n**Author:** Jeroen Demeyer\n\n**Merged:** sage-5.9.beta0\n\nIssue created by migration from https://trac.sagemath.org/ticket/14079\n\n",
    "closed_at": "2013-03-14T08:10:29Z",
    "created_at": "2013-02-07T13:00:59Z",
    "labels": [
        "component: misc",
        "enhancement"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-5.9",
    "title": "Cython interface to pselect() system call",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/14079",
    "user": "https://github.com/jdemeyer"
}
```
Useful for the new doctesting framework.

Depends on #14080

Depends on #12415

**Assignee:** @jasongrout

**Reviewer:** Volker Braun

**Author:** Jeroen Demeyer

**Merged:** sage-5.9.beta0

Issue created by migration from https://trac.sagemath.org/ticket/14079





---

archive/issue_comments_169748.json:
```json
{
    "body": "**Dependencies:** #14080",
    "created_at": "2013-02-07T15:08:52Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169748",
    "user": "https://github.com/jdemeyer"
}
```

**Dependencies:** #14080



---

archive/issue_comments_169749.json:
```json
{
    "body": "<a id='comment:2'></a>\nI'm intentionally not setting it to needs_review yet, because I want to first have a use case (that will be #12415). But that being said, the code here is supposed to be finished.",
    "created_at": "2013-02-11T09:07:44Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169749",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:2'></a>
I'm intentionally not setting it to needs_review yet, because I want to first have a use case (that will be #12415). But that being said, the code here is supposed to be finished.



---

archive/issue_comments_169750.json:
```json
{
    "body": "<a id='comment:3'></a>\nTesting on 5.6 I get a doctest framework error (since you use the new `....:` continuation).  But testing on 5.7.beta1 with #12415 I get a timeout on line 308 (`r, w, x, t = PSelecter().pselect([f,g,f,f,g])`).",
    "created_at": "2013-02-11T14:18:14Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169750",
    "user": "https://github.com/roed314"
}
```

<a id='comment:3'></a>
Testing on 5.6 I get a doctest framework error (since you use the new `....:` continuation).  But testing on 5.7.beta1 with #12415 I get a timeout on line 308 (`r, w, x, t = PSelecter().pselect([f,g,f,f,g])`).



---

archive/issue_comments_169751.json:
```json
{
    "body": "<a id='comment:4'></a>\nReplying to [@roed314](#comment%3A3):\n> with #12415 I get a timeout on line 308 (`r, w, x, t = PSelecter().pselect([f,g,f,f,g])`).\n\nOn which kind of system is that?",
    "created_at": "2013-02-11T14:25:14Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169751",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:4'></a>
Replying to [@roed314](#comment%3A3):
> with #12415 I get a timeout on line 308 (`r, w, x, t = PSelecter().pselect([f,g,f,f,g])`).

On which kind of system is that?



---

archive/issue_comments_169752.json:
```json
{
    "body": "<a id='comment:5'></a>\nReplying to [@jdemeyer](#comment%3A4):\n> Replying to [@roed314](#comment%3A3):\n> > with #12415 I get a timeout on line 308 (`r, w, x, t = PSelecter().pselect([f,g,f,f,g])`).\n\n> On which kind of system is that?\n\nOS X 10.6.8, Core 2 Duo.",
    "created_at": "2013-02-11T14:31:24Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169752",
    "user": "https://github.com/roed314"
}
```

<a id='comment:5'></a>
Replying to [@jdemeyer](#comment%3A4):
> Replying to [@roed314](#comment%3A3):
> > with #12415 I get a timeout on line 308 (`r, w, x, t = PSelecter().pselect([f,g,f,f,g])`).

> On which kind of system is that?

OS X 10.6.8, Core 2 Duo.



---

archive/issue_comments_169753.json:
```json
{
    "body": "<a id='comment:6'></a>\nUpdated patch (I haven't looked at the OS X specific issue).",
    "created_at": "2013-02-12T17:28:34Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169753",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:6'></a>
Updated patch (I haven't looked at the OS X specific issue).



---

archive/issue_comments_169754.json:
```json
{
    "body": "<a id='comment:7'></a>\nSee http://stackoverflow.com/questions/14045801/different-pselect-behaviour-on-osx-vs-linux for a possible explanation of what's going on on OS X.",
    "created_at": "2013-02-12T20:01:09Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169754",
    "user": "https://github.com/roed314"
}
```

<a id='comment:7'></a>
See http://stackoverflow.com/questions/14045801/different-pselect-behaviour-on-osx-vs-linux for a possible explanation of what's going on on OS X.



---

archive/issue_comments_169755.json:
```json
{
    "body": "<a id='comment:8'></a>\nThanks for the pointer, but that doesn't seem to be the problem: no signals are involved in the failing tests you mention.",
    "created_at": "2013-02-12T21:59:14Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169755",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:8'></a>
Thanks for the pointer, but that doesn't seem to be the problem: no signals are involved in the failing tests you mention.



---

archive/issue_events_121964.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-02-23T00:29:14Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121964"
}
```



---

archive/issue_comments_169756.json:
```json
{
    "body": "<a id='comment:9'></a>\nNew version, works for me on OS X 10.6 with the latest version of #12415. Note that parallel testing on OS X is broken, but normal testing (with `-p 1`) works.",
    "created_at": "2013-02-23T00:29:14Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169756",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:9'></a>
New version, works for me on OS X 10.6 with the latest version of #12415. Note that parallel testing on OS X is broken, but normal testing (with `-p 1`) works.



---

archive/issue_comments_169757.json:
```json
{
    "body": "<a id='comment:10'></a>\nApply failed....",
    "created_at": "2013-02-24T11:24:00Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169757",
    "user": "https://github.com/roed314"
}
```

<a id='comment:10'></a>
Apply failed....



---

archive/issue_events_121965.json:
```json
{
    "actor": "https://github.com/roed314",
    "created_at": "2013-02-24T11:24:08Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121965"
}
```



---

archive/issue_events_121966.json:
```json
{
    "actor": "https://github.com/roed314",
    "created_at": "2013-02-24T11:24:08Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121966"
}
```



---

archive/attachments_019650.json:
```json
{
    "asset_content_type": "application/octet-stream",
    "asset_name": "14079_pselecter.patch",
    "asset_url": "tarball://root/attachments/ticket14079/14079_pselecter.patch",
    "created_at": "2013-02-25T11:01:34Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "attachment",
    "url": "https://github.com/sagemath/sage/files/ticket14079/14079_pselecter.patch",
    "user": "https://github.com/jdemeyer"
}
```



---

archive/issue_comments_169758.json:
```json
{
    "body": "<a id='comment:12'></a>\n**Attachment:** [14079_pselecter.patch](https://github.com/sagemath/sage/files/ticket14079/14079_pselecter.patch)",
    "created_at": "2013-02-25T11:01:34Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169758",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:12'></a>
**Attachment:** [14079_pselecter.patch](https://github.com/sagemath/sage/files/ticket14079/14079_pselecter.patch)



---

archive/issue_events_121967.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-02-25T11:01:34Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121967"
}
```



---

archive/issue_events_121968.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-02-25T11:01:34Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121968"
}
```



---

archive/issue_comments_169759.json:
```json
{
    "body": "<a id='comment:13'></a>\nWhat was the problem on OS X?",
    "created_at": "2013-02-25T11:52:33Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169759",
    "user": "https://github.com/roed314"
}
```

<a id='comment:13'></a>
What was the problem on OS X?



---

archive/issue_comments_169760.json:
```json
{
    "body": "<a id='comment:14'></a>\nThe problem on OS X is:\n\n```\nsage: import select\nsage: f = open(os.devnull)\nsage: select.select([],[],[f])\n([], [], [<open file '/dev/null', mode 'r' at 0x113ac7420>])\n```\nFor some reason, most files have an \"exceptional condition\" by default on OS X. I have no idea why or what this means.",
    "created_at": "2013-02-25T12:17:49Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169760",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:14'></a>
The problem on OS X is:

```
sage: import select
sage: f = open(os.devnull)
sage: select.select([],[],[f])
([], [], [<open file '/dev/null', mode 'r' at 0x113ac7420>])
```
For some reason, most files have an "exceptional condition" by default on OS X. I have no idea why or what this means.



---

archive/issue_comments_169761.json:
```json
{
    "body": "<a id='comment:15'></a>\nSo is this causing the problems for parallel testing on OS X?  Do you know how to get around it?",
    "created_at": "2013-02-25T12:30:54Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169761",
    "user": "https://github.com/roed314"
}
```

<a id='comment:15'></a>
So is this causing the problems for parallel testing on OS X?  Do you know how to get around it?



---

archive/issue_comments_169762.json:
```json
{
    "body": "<a id='comment:16'></a>\nReplying to [@roed314](#comment%3A15):\n> So is this causing the problems for parallel testing on OS X?\n\nNo, this has nothing to do with parallel. The parallel testing should be fixed now.\n\nThe parallel testing problem with #12415 on OS X was due to `Pdb()` importing `readline`. Importing readline hangs (probably because more than one process tries to take control over the terminal somehow). The solution is simply not starting `Pdb` if not needed.",
    "created_at": "2013-02-25T13:43:10Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169762",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:16'></a>
Replying to [@roed314](#comment%3A15):
> So is this causing the problems for parallel testing on OS X?

No, this has nothing to do with parallel. The parallel testing should be fixed now.

The parallel testing problem with #12415 on OS X was due to `Pdb()` importing `readline`. Importing readline hangs (probably because more than one process tries to take control over the terminal somehow). The solution is simply not starting `Pdb` if not needed.



---

archive/issue_comments_169763.json:
```json
{
    "body": "**Changing dependencies** from \"#14080\" to \"#14080, #12415\".",
    "created_at": "2013-02-28T10:13:26Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169763",
    "user": "https://github.com/jdemeyer"
}
```

**Changing dependencies** from "#14080" to "#14080, #12415".



---

archive/issue_comments_169764.json:
```json
{
    "body": "<a id='comment:18'></a>\nLooks good to me. Doesn't actually depend on #12415",
    "created_at": "2013-02-28T19:35:24Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169764",
    "user": "https://github.com/vbraun"
}
```

<a id='comment:18'></a>
Looks good to me. Doesn't actually depend on #12415



---

archive/issue_comments_169765.json:
```json
{
    "body": "**Reviewer:** Volker Braun",
    "created_at": "2013-02-28T19:35:24Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169765",
    "user": "https://github.com/vbraun"
}
```

**Reviewer:** Volker Braun



---

archive/issue_comments_169766.json:
```json
{
    "body": "**Changing dependencies** from \"#14080, #12415\" to \"#14080\".",
    "created_at": "2013-02-28T19:35:24Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169766",
    "user": "https://github.com/vbraun"
}
```

**Changing dependencies** from "#14080, #12415" to "#14080".



---

archive/issue_events_121969.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2013-02-28T19:39:42Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121969"
}
```



---

archive/issue_events_121970.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2013-02-28T19:39:42Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121970"
}
```



---

archive/issue_comments_169767.json:
```json
{
    "body": "<a id='comment:19'></a>\nI get the following:\n\n```\nTraceback (most recent call last):\n  File \"/home/vbraun/.sage//tmp/pselect_21760.py\", line 458, in <module>\n    runner=runner)\n  File \"/home/vbraun/opt/sage-5.8.beta1/local/bin/sagedoctest.py\", line 54, in testmod_returning_runner\n    runner=runner)\n  File \"/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py\", line 1819, in testmod_returning_runner\n    for test in finder.find(m, name, globs=globs, extraglobs=extraglobs):\n  File \"/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py\", line 839, in find\n    self._find(tests, obj, name, module, source_lines, globs, {})\n  File \"/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py\", line 893, in _find\n    globs, seen)\n  File \"/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py\", line 881, in _find\n    test = self._get_test(obj, name, module, globs, source_lines)\n  File \"/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py\", line 965, in _get_test\n    filename, lineno)\n  File \"/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py\", line 594, in get_doctest\n    return DocTest(self.get_examples(string, name), globs,\n  File \"/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py\", line 608, in get_examples\n    return [x for x in self.parse(string, name)\n  File \"/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py\", line 570, in parse\n    self._parse_example(m, name, lineno)\n  File \"/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py\", line 628, in _parse_example\n    self._check_prompt_blank(source_lines, indent, name, lineno)\n  File \"/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py\", line 715, in _check_prompt_blank\n    line[indent:indent+3], line))\nValueError: line 14 of the docstring for __main__.example_6 lacks blank after ...: '            ....:     global got_child'\nException raised by doctesting framework. Use -verbose for details.\n```",
    "created_at": "2013-02-28T19:39:42Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169767",
    "user": "https://github.com/vbraun"
}
```

<a id='comment:19'></a>
I get the following:

```
Traceback (most recent call last):
  File "/home/vbraun/.sage//tmp/pselect_21760.py", line 458, in <module>
    runner=runner)
  File "/home/vbraun/opt/sage-5.8.beta1/local/bin/sagedoctest.py", line 54, in testmod_returning_runner
    runner=runner)
  File "/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py", line 1819, in testmod_returning_runner
    for test in finder.find(m, name, globs=globs, extraglobs=extraglobs):
  File "/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py", line 839, in find
    self._find(tests, obj, name, module, source_lines, globs, {})
  File "/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py", line 893, in _find
    globs, seen)
  File "/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py", line 881, in _find
    test = self._get_test(obj, name, module, globs, source_lines)
  File "/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py", line 965, in _get_test
    filename, lineno)
  File "/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py", line 594, in get_doctest
    return DocTest(self.get_examples(string, name), globs,
  File "/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py", line 608, in get_examples
    return [x for x in self.parse(string, name)
  File "/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py", line 570, in parse
    self._parse_example(m, name, lineno)
  File "/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py", line 628, in _parse_example
    self._check_prompt_blank(source_lines, indent, name, lineno)
  File "/home/vbraun/opt/sage-5.8.beta1/local/bin/ncadoctest.py", line 715, in _check_prompt_blank
    line[indent:indent+3], line))
ValueError: line 14 of the docstring for __main__.example_6 lacks blank after ...: '            ....:     global got_child'
Exception raised by doctesting framework. Use -verbose for details.
```



---

archive/issue_events_121971.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-02-28T19:42:10Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121971"
}
```



---

archive/issue_events_121972.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-02-28T19:42:10Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121972"
}
```



---

archive/issue_comments_169768.json:
```json
{
    "body": "<a id='comment:20'></a>\nReplying to [@vbraun](#comment%3A19):\n> I get the following:\n> \n> ```\n> Exception raised by doctesting framework. Use -verbose for details.\n> ```\n\nThat's exactly why there was a dependency on #12415, I'm using new doctest syntax.",
    "created_at": "2013-02-28T19:42:10Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169768",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:20'></a>
Replying to [@vbraun](#comment%3A19):
> I get the following:
> 
> ```
> Exception raised by doctesting framework. Use -verbose for details.
> ```

That's exactly why there was a dependency on #12415, I'm using new doctest syntax.



---

archive/issue_comments_169769.json:
```json
{
    "body": "**Changing dependencies** from \"#14080\" to \"#14080, #12415\".",
    "created_at": "2013-02-28T19:42:10Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169769",
    "user": "https://github.com/jdemeyer"
}
```

**Changing dependencies** from "#14080" to "#14080, #12415".



---

archive/issue_events_121973.json:
```json
{
    "actor": "https://github.com/roed314",
    "created_at": "2013-03-01T01:57:13Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121973"
}
```



---

archive/issue_events_121974.json:
```json
{
    "actor": "https://github.com/roed314",
    "created_at": "2013-03-01T01:57:13Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121974"
}
```



---

archive/issue_comments_169770.json:
```json
{
    "body": "<a id='comment:21'></a>\nI just talked to Volker.  Looks good to us.",
    "created_at": "2013-03-01T01:57:13Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169770",
    "user": "https://github.com/roed314"
}
```

<a id='comment:21'></a>
I just talked to Volker.  Looks good to us.



---

archive/issue_events_121975.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-03-01T19:25:17Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "milestone": "sage-5.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121975"
}
```



---

archive/issue_events_121976.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-03-01T19:25:17Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "milestone": "sage-5.9",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121976"
}
```



---

archive/issue_events_121977.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-03-14T08:10:29Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121977"
}
```



---

archive/issue_events_121978.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-03-14T08:10:29Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14079#event-121978"
}
```



---

archive/issue_comments_169771.json:
```json
{
    "body": "**Merged:** sage-5.9.beta0",
    "created_at": "2013-03-14T08:10:29Z",
    "issue": "https://github.com/sagemath/sage/issues/14079",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14079#issuecomment-169771",
    "user": "https://github.com/jdemeyer"
}
```

**Merged:** sage-5.9.beta0
