# Issue 14670: Intraceable error messages

archive/issues_014466.json:
```json
{
    "body": "SAGE swarms by useless pseudo-error messages like\n\n\"Negative number cannot be raised to a fractional power\"\n\nor\n\n\"maximum recursion depth exceeded while getting the str of an object\"\n\nOnce these appear, there is no other way to finding the cause than bisecting the code. Please keep an eye open while you work on the source and replace these things by proper errors, which can be backtraced, when you come across them.\n\n**Assignee:** @jasongrout\n\nIssue created by migration from https://trac.sagemath.org/ticket/14670\n\n",
    "created_at": "2013-05-30T21:48:41Z",
    "labels": [
        "component: misc",
        "bug"
    ],
    "title": "Intraceable error messages",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/14670",
    "user": "https://trac.sagemath.org/admin/accounts/users/ManDay"
}
```
SAGE swarms by useless pseudo-error messages like

"Negative number cannot be raised to a fractional power"

or

"maximum recursion depth exceeded while getting the str of an object"

Once these appear, there is no other way to finding the cause than bisecting the code. Please keep an eye open while you work on the source and replace these things by proper errors, which can be backtraced, when you come across them.

**Assignee:** @jasongrout

Issue created by migration from https://trac.sagemath.org/ticket/14670





---

archive/issue_comments_180653.json:
```json
{
    "body": "<a id='comment:1'></a>\nHow do we know when we can close this ticket?\n\nFrom the description, it sounds like this caution might be better suited as a post to sage-devel about general development advice, or maybe a patch to the developer's guide.",
    "created_at": "2013-05-30T22:03:33Z",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14670#issuecomment-180653",
    "user": "https://github.com/jasongrout"
}
```

<a id='comment:1'></a>
How do we know when we can close this ticket?

From the description, it sounds like this caution might be better suited as a post to sage-devel about general development advice, or maybe a patch to the developer's guide.



---

archive/issue_comments_180654.json:
```json
{
    "body": "<a id='comment:2'></a>\nFair enough, how about closing this ticket once the two error messages above have been adressed (assuming you agree that this is indeed a problem)?",
    "created_at": "2013-05-30T22:43:20Z",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14670#issuecomment-180654",
    "user": "https://trac.sagemath.org/admin/accounts/users/ManDay"
}
```

<a id='comment:2'></a>
Fair enough, how about closing this ticket once the two error messages above have been adressed (assuming you agree that this is indeed a problem)?



---

archive/issue_comments_180655.json:
```json
{
    "body": "<a id='comment:3'></a>\nThese error messages don't appear anywhere in the Sage code:\n\n```\nsage: search_src('number', 'cannot', 'raised')\n\nsage: search_src('getting', 'str', 'object')\n\n```\nCan you provide explicit examples showing these error messages?",
    "created_at": "2013-05-30T23:03:35Z",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14670#issuecomment-180655",
    "user": "https://github.com/jhpalmieri"
}
```

<a id='comment:3'></a>
These error messages don't appear anywhere in the Sage code:

```
sage: search_src('number', 'cannot', 'raised')

sage: search_src('getting', 'str', 'object')

```
Can you provide explicit examples showing these error messages?



---

archive/issue_comments_180656.json:
```json
{
    "body": "<a id='comment:4'></a>\nThe error message about negative numbers is the same you get when\n\n( float(-3) )**( 1/2 )\n\nwith the only difference, that in this case, it's a real ValueError. If I recall correctly, I often got such pseudo errors from somewhere in the execution stack of minimize( ) or minimize_constrained( ).\n\nI can't readily reproduce it right now (or only with a huge code), but as soon as I've found a better example, I'll submit it.",
    "created_at": "2013-05-31T06:46:42Z",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14670#issuecomment-180656",
    "user": "https://trac.sagemath.org/admin/accounts/users/ManDay"
}
```

<a id='comment:4'></a>
The error message about negative numbers is the same you get when

( float(-3) )**( 1/2 )

with the only difference, that in this case, it's a real ValueError. If I recall correctly, I often got such pseudo errors from somewhere in the execution stack of minimize( ) or minimize_constrained( ).

I can't readily reproduce it right now (or only with a huge code), but as soon as I've found a better example, I'll submit it.



---

archive/issue_events_128839.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-08-13T15:35:53Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "milestone": "sage-5.11",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14670#event-128839"
}
```



---

archive/issue_events_128840.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-08-13T15:35:53Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "milestone": "sage-5.12",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14670#event-128840"
}
```



---

archive/issue_events_128841.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-01-30T21:20:52Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "milestone": "sage-6.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14670#event-128841"
}
```



---

archive/issue_events_128842.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-01-30T21:20:52Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "milestone": "sage-6.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14670#event-128842"
}
```



---

archive/issue_events_128843.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-05-06T15:20:58Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "milestone": "sage-6.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14670#event-128843"
}
```



---

archive/issue_events_128844.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-05-06T15:20:58Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "milestone": "sage-6.3",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14670#event-128844"
}
```



---

archive/issue_events_128845.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-08-10T16:51:03Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "milestone": "sage-6.3",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14670#event-128845"
}
```



---

archive/issue_events_128846.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-08-10T16:51:03Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "milestone": "sage-6.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14670#event-128846"
}
```



---

archive/issue_events_128847.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2022-12-29T01:28:25Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/14670",
    "milestone": "sage-6.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14670#event-128847"
}
```
