# Issue 15275: Make "sage -c 'attach(...); print 3'" work right

archive/issues_015038.json:
```json
{
    "body": "This was first reported on [stackoverflow](http://stackoverflow.com/questions/19344741/python-sage-attach-from-command-line-and-run-another-command).\n\nWhile running Sage:\n\n```\nsage: attach(\"file.sage\"); print 3\n```\nworks, but from the shell:\n\n```\n$ sage -c \"attach('file.sage'); print 3\"\n```\nfails. It actually tries to execute the command\n\n```\nsage \"/path/to/'file.sage'; print Integer(2)\"\n```\nand so it tries to read everything between the first and last quotes as the file name, thus producing the error\n\n```\npython: can't open file '/path/to/'file.sage'; print Integer(2)': [Errno 2] No such file or directory\n```\nThis is because the script `sage-eval` tries to do something clever when the command to be executed starts with `attach` or `load`, but it is assuming that the rest of the command consists entirely of the file name.\n\n\n\n\n**Branch/Commit:** [fdc586f44213fd7f4af050690ec7371b9a8f2146](https://github.com/sagemath/sagetrac-mirror/commit/fdc586f44213fd7f4af050690ec7371b9a8f2146)\n\n**Reviewer:** Jeroen Demeyer\n\n**Author:** Andr\u00e9 Apitzsch\n\nIssue created by migration from https://trac.sagemath.org/ticket/15275\n\n",
    "closed_at": "2015-01-24T13:18:37Z",
    "created_at": "2013-10-13T18:27:35Z",
    "labels": [
        "component: scripts",
        "minor",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-6.5",
    "title": "Make \"sage -c 'attach(...); print 3'\" work right",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/15275",
    "user": "https://github.com/jhpalmieri"
}
```
This was first reported on [stackoverflow](http://stackoverflow.com/questions/19344741/python-sage-attach-from-command-line-and-run-another-command).

While running Sage:

```
sage: attach("file.sage"); print 3
```
works, but from the shell:

```
$ sage -c "attach('file.sage'); print 3"
```
fails. It actually tries to execute the command

```
sage "/path/to/'file.sage'; print Integer(2)"
```
and so it tries to read everything between the first and last quotes as the file name, thus producing the error

```
python: can't open file '/path/to/'file.sage'; print Integer(2)': [Errno 2] No such file or directory
```
This is because the script `sage-eval` tries to do something clever when the command to be executed starts with `attach` or `load`, but it is assuming that the rest of the command consists entirely of the file name.




**Branch/Commit:** [fdc586f44213fd7f4af050690ec7371b9a8f2146](https://github.com/sagemath/sagetrac-mirror/commit/fdc586f44213fd7f4af050690ec7371b9a8f2146)

**Reviewer:** Jeroen Demeyer

**Author:** André Apitzsch

Issue created by migration from https://trac.sagemath.org/ticket/15275





---

archive/issue_events_135280.json:
```json
{
    "actor": "https://github.com/jhpalmieri",
    "created_at": "2013-10-13T18:27:43Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "label": "minor",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135280"
}
```



---

archive/issue_events_135281.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-01-30T21:20:52Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "milestone": "sage-6.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135281"
}
```



---

archive/issue_events_135282.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-01-30T21:20:52Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "milestone": "sage-6.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135282"
}
```



---

archive/issue_events_135283.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-05-06T15:20:58Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "milestone": "sage-6.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135283"
}
```



---

archive/issue_events_135284.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-05-06T15:20:58Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "milestone": "sage-6.3",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135284"
}
```



---

archive/issue_events_135285.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-08-10T16:51:03Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "milestone": "sage-6.3",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135285"
}
```



---

archive/issue_events_135286.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-08-10T16:51:03Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "milestone": "sage-6.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135286"
}
```



---

archive/issue_comments_190962.json:
```json
{
    "body": "<a id='comment:5'></a>\nProblem was introduced by #508.\nSince I couldn't find an answer why `./sage -c \"attach file.sage\"` was supposed to work, I suggest to revert the changes made in #508.",
    "created_at": "2015-01-09T15:47:59Z",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/15275#issuecomment-190962",
    "user": "https://github.com/a-andre"
}
```

<a id='comment:5'></a>
Problem was introduced by #508.
Since I couldn't find an answer why `./sage -c "attach file.sage"` was supposed to work, I suggest to revert the changes made in #508.



---

archive/issue_comments_190963.json:
```json
{
    "body": "<a id='comment:6'></a>\n+1 to undo the \"something clever\"",
    "created_at": "2015-01-11T21:16:21Z",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/15275#issuecomment-190963",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:6'></a>
+1 to undo the "something clever"



---

archive/issue_events_135287.json:
```json
{
    "actor": "https://github.com/a-andre",
    "created_at": "2015-01-11T22:23:13Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135287"
}
```



---

archive/issue_comments_190964.json:
```json
{
    "body": "**Commit:** [fdc586f44213fd7f4af050690ec7371b9a8f2146](https://github.com/sagemath/sagetrac-mirror/commit/fdc586f44213fd7f4af050690ec7371b9a8f2146)",
    "created_at": "2015-01-11T22:23:13Z",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/15275#issuecomment-190964",
    "user": "https://github.com/a-andre"
}
```

**Commit:** [fdc586f44213fd7f4af050690ec7371b9a8f2146](https://github.com/sagemath/sagetrac-mirror/commit/fdc586f44213fd7f4af050690ec7371b9a8f2146)



---

archive/issue_comments_190965.json:
```json
{
    "body": "**Author:** Andr\u00e9 Apitzsch",
    "created_at": "2015-01-11T22:23:13Z",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/15275#issuecomment-190965",
    "user": "https://github.com/a-andre"
}
```

**Author:** André Apitzsch



---

archive/issue_comments_190966.json:
```json
{
    "body": "**Branch:** [u/aapitzsch/ticket/15275](https://github.com/sagemath/sagetrac-mirror/tree/u/aapitzsch/ticket/15275)",
    "created_at": "2015-01-11T22:23:13Z",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/15275#issuecomment-190966",
    "user": "https://github.com/a-andre"
}
```

**Branch:** [u/aapitzsch/ticket/15275](https://github.com/sagemath/sagetrac-mirror/tree/u/aapitzsch/ticket/15275)



---

archive/issue_events_135288.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2015-01-20T12:00:39Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135288"
}
```



---

archive/issue_events_135289.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2015-01-20T12:00:39Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135289"
}
```



---

archive/issue_events_135290.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2015-01-20T12:00:39Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "milestone": "sage-6.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135290"
}
```



---

archive/issue_events_135291.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2015-01-20T12:00:39Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "milestone": "sage-6.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135291"
}
```



---

archive/issue_comments_190967.json:
```json
{
    "body": "**Reviewer:** Jeroen Demeyer",
    "created_at": "2015-01-20T12:00:39Z",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/15275#issuecomment-190967",
    "user": "https://github.com/jdemeyer"
}
```

**Reviewer:** Jeroen Demeyer



---

archive/issue_comments_190968.json:
```json
{
    "body": "**Changing branch** from \"[u/aapitzsch/ticket/15275](https://github.com/sagemath/sagetrac-mirror/tree/u/aapitzsch/ticket/15275)\" to \"[fdc586f44213fd7f4af050690ec7371b9a8f2146](https://github.com/sagemath/sagetrac-mirror/commit/fdc586f44213fd7f4af050690ec7371b9a8f2146)\".",
    "created_at": "2015-01-24T13:18:37Z",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/15275#issuecomment-190968",
    "user": "https://github.com/vbraun"
}
```

**Changing branch** from "[u/aapitzsch/ticket/15275](https://github.com/sagemath/sagetrac-mirror/tree/u/aapitzsch/ticket/15275)" to "[fdc586f44213fd7f4af050690ec7371b9a8f2146](https://github.com/sagemath/sagetrac-mirror/commit/fdc586f44213fd7f4af050690ec7371b9a8f2146)".



---

archive/issue_events_135292.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2015-01-24T13:18:37Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135292"
}
```



---

archive/issue_events_135293.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "cff923ceaca9b861d4f6e4b63020be048bec5881",
    "created_at": "2015-01-24T13:18:37Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/15275",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/15275#event-135293"
}
```
