# Issue 24271: py3: allow flexibility in exception message formatting in doctests on Python 3

archive/issues_024034.json:
```json
{
    "assignees": [],
    "body": "<div id=\"comment:0\"></div>\n\nOn Python 2 exception messages are printed, along with the exception class name, like\n\n```\nSignError: cannot multiply infinity by zero\n```\n\nwhereas on Python 3 they're printed with the exception class's fully qualified name (for non-builtin exceptions):\n\n```\nsage.rings.infinity.SignError: cannot multiply infinity by zero\n```\n\nTherefore any doctest that expects a traceback fails, due to this slight formatting difference.  One can go through all such tests and insert ellipses.  But it's simpler if we just normalize for this trivial formatting difference, similarly to #24258.\n\nAdditionally, there were a few common exceptions (particularly `IOError` which [as of Python 3.3](https://docs.python.org/3/library/exceptions.html#OSError) are just aliases for `OSError`, so we handle that case as well.\n\nIn this case the fixup isn't done directly in the `OutputChecker` since, in order to make this normalization as restrictive as possible, we need access to the exception info which is not normally passed to `OutputChecker`.  So this is handled directly in `SageDocTestRunner`'s result handling.\n\nThis made a lot of previously \"failing\" tests pass for me.  But it should be made clear that this normalization does not in any way take away from the validity of the tests.\n\nComponent: **python3**\n\nAuthor: **Erik Bray**\n\nBranch/Commit: **[`9a659d8`](https://github.com/sagemath/sagetrac-mirror/commit/9a659d831cb431c6884d22c715fecc4cda9a6b61)**\n\nReviewer: **Jeroen Demeyer**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/24271_\n\n",
    "closed_at": "2017-12-13T17:38:05Z",
    "created_at": "2017-11-23T09:33:37Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20python3",
        "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
        "https://github.com/sagemath/sage/labels/enhancement"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-8.2",
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "py3: allow flexibility in exception message formatting in doctests on Python 3",
    "type": "issue",
    "updated_at": "2017-12-13T17:38:05Z",
    "url": "https://github.com/sagemath/sage/issues/24271",
    "user": "https://github.com/embray"
}
```
<div id="comment:0"></div>

On Python 2 exception messages are printed, along with the exception class name, like

```
SignError: cannot multiply infinity by zero
```

whereas on Python 3 they're printed with the exception class's fully qualified name (for non-builtin exceptions):

```
sage.rings.infinity.SignError: cannot multiply infinity by zero
```

Therefore any doctest that expects a traceback fails, due to this slight formatting difference.  One can go through all such tests and insert ellipses.  But it's simpler if we just normalize for this trivial formatting difference, similarly to #24258.

Additionally, there were a few common exceptions (particularly `IOError` which [as of Python 3.3](https://docs.python.org/3/library/exceptions.html#OSError) are just aliases for `OSError`, so we handle that case as well.

In this case the fixup isn't done directly in the `OutputChecker` since, in order to make this normalization as restrictive as possible, we need access to the exception info which is not normally passed to `OutputChecker`.  So this is handled directly in `SageDocTestRunner`'s result handling.

This made a lot of previously "failing" tests pass for me.  But it should be made clear that this normalization does not in any way take away from the validity of the tests.

Component: **python3**

Author: **Erik Bray**

Branch/Commit: **[`9a659d8`](https://github.com/sagemath/sagetrac-mirror/commit/9a659d831cb431c6884d22c715fecc4cda9a6b61)**

Reviewer: **Jeroen Demeyer**

_Issue created by migration from https://trac.sagemath.org/ticket/24271_





---

archive/issue_events_333968.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-11-23T09:33:37Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "milestone_number": null,
    "milestone_title": "sage-8.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333968"
}
```



---

archive/issue_events_333969.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-11-23T09:33:37Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20python3",
    "label_color": "0000b0",
    "label_name": "c: python3",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333969"
}
```



---

archive/issue_events_333970.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-11-23T09:33:37Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
    "label_color": "ffbb00",
    "label_name": "p: major / 3",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333970"
}
```



---

archive/issue_events_333971.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-11-23T09:33:37Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/enhancement",
    "label_color": "696969",
    "label_name": "enhancement",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333971"
}
```



---

archive/issue_events_333972.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-11-23T09:34:04Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333972"
}
```



---

archive/issue_comments_367423.json:
```json
{
    "body": "<div id=\"comment:2\"></div>\n\nBranch pushed to git repo; I updated commit sha1. This was a forced push. New commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/fc905d7c9b141834628cdfcc854e280e4704ceab\"><code>fc905d7</code></a></td><td><code>Better support on Python 3 for doctests that expect exceptions.</code></td></tr></table>\n",
    "created_at": "2017-11-23T11:16:09Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367423",
    "user": "https://github.com/sagetrac-git"
}
```

<div id="comment:2"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/fc905d7c9b141834628cdfcc854e280e4704ceab"><code>fc905d7</code></a></td><td><code>Better support on Python 3 for doctests that expect exceptions.</code></td></tr></table>




---

archive/issue_comments_367424.json:
```json
{
    "body": "Changed commit from **[`6b31808`](https://github.com/sagemath/sagetrac-mirror/commit/6b31808c7e765636b049214c7055c6eaf2783550)** to **[`fc905d7`](https://github.com/sagemath/sagetrac-mirror/commit/fc905d7c9b141834628cdfcc854e280e4704ceab)**",
    "created_at": "2017-11-23T11:16:09Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367424",
    "user": "https://github.com/sagetrac-git"
}
```

Changed commit from **[`6b31808`](https://github.com/sagemath/sagetrac-mirror/commit/6b31808c7e765636b049214c7055c6eaf2783550)** to **[`fc905d7`](https://github.com/sagemath/sagetrac-mirror/commit/fc905d7c9b141834628cdfcc854e280e4704ceab)**



---

archive/issue_comments_367425.json:
```json
{
    "body": "<div id=\"comment:3\" align=\"right\">comment:3</div>\n\nsee also #16088",
    "created_at": "2017-11-23T13:07:00Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367425",
    "user": "https://github.com/fchapoton"
}
```

<div id="comment:3" align="right">comment:3</div>

see also #16088



---

archive/issue_comments_367426.json:
```json
{
    "body": "<div id=\"comment:4\" align=\"right\">comment:4</div>\n\nInteresting--it might also be worth addressing some of those common differences between built-in exception messages.  Are there any other examples besides `ZeroDivision`?",
    "created_at": "2017-11-23T14:00:43Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367426",
    "user": "https://github.com/embray"
}
```

<div id="comment:4" align="right">comment:4</div>

Interesting--it might also be worth addressing some of those common differences between built-in exception messages.  Are there any other examples besides `ZeroDivision`?



---

archive/issue_comments_367427.json:
```json
{
    "body": "<div id=\"comment:5\" align=\"right\">comment:5</div>\n\nNO idea. I was keeping that for stage C (make the doctests pass) after stage B (make vanilla-sage start with python 3). Stage A (make vanilla-sage build with python 3) is done already. We have some hope to see stage B completed soon, maybe.",
    "created_at": "2017-11-23T15:09:35Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367427",
    "user": "https://github.com/fchapoton"
}
```

<div id="comment:5" align="right">comment:5</div>

NO idea. I was keeping that for stage C (make the doctests pass) after stage B (make vanilla-sage start with python 3). Stage A (make vanilla-sage build with python 3) is done already. We have some hope to see stage B completed soon, maybe.



---

archive/issue_comments_367428.json:
```json
{
    "body": "<div id=\"comment:6\" align=\"right\">comment:6</div>\n\nI'm still pretty near to having the doctester 100% working too.  I'm just working out a few more small kinks.",
    "created_at": "2017-11-23T15:57:19Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367428",
    "user": "https://github.com/embray"
}
```

<div id="comment:6" align="right">comment:6</div>

I'm still pretty near to having the doctester 100% working too.  I'm just working out a few more small kinks.



---

archive/issue_comments_367429.json:
```json
{
    "body": "<div id=\"comment:7\" align=\"right\">comment:7</div>\n\n1. Why this check?\n\n```\nif exc_info[0].__module__\n```\nAre there any cases where `__module__` would *not* be a `True` value?\n\n2. You really want to use `__qualname__` instead of `__name__` on Python 3, since that is what the `traceback` module uses.\n\nFor reference, this is the relevant code from the `traceback` module:\n\n```\n        stype = self.exc_type.__qualname__\n        smod = self.exc_type.__module__\n        if smod not in (\"__main__\", \"builtins\"):\n            stype = smod + '.' + stype\n```",
    "created_at": "2017-11-24T09:57:44Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367429",
    "user": "https://github.com/jdemeyer"
}
```

<div id="comment:7" align="right">comment:7</div>

1. Why this check?

```
if exc_info[0].__module__
```
Are there any cases where `__module__` would *not* be a `True` value?

2. You really want to use `__qualname__` instead of `__name__` on Python 3, since that is what the `traceback` module uses.

For reference, this is the relevant code from the `traceback` module:

```
        stype = self.exc_type.__qualname__
        smod = self.exc_type.__module__
        if smod not in ("__main__", "builtins"):
            stype = smod + '.' + stype
```



---

archive/issue_events_333973.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-11-24T09:57:44Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333973"
}
```



---

archive/issue_events_333974.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-11-24T09:57:44Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333974"
}
```



---

archive/issue_comments_367430.json:
```json
{
    "body": "<div id=\"comment:8\" align=\"right\">comment:8</div>\n\n3. `exc_qualname` is a confusing name. Better use `exc_fullname` or something.",
    "created_at": "2017-11-24T09:59:31Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367430",
    "user": "https://github.com/jdemeyer"
}
```

<div id="comment:8" align="right">comment:8</div>

3. `exc_qualname` is a confusing name. Better use `exc_fullname` or something.



---

archive/issue_comments_367431.json:
```json
{
    "body": "<div id=\"comment:9\" align=\"right\">comment:9</div>\n\nReplying to [@jdemeyer](#comment%3A7):\n> 1. Why this check?\n> \n> ```\n> if exc_info[0].__module__\n> ```\n> Are there any cases where `__module__` would *not* be a `True` value?\n\nWhile I can't name an exact case off the top of my head, I've seen pathological cases (especially in the context of dynamically created classes) where `__module__` can be `None`.  For functions and methods it can definitely be `None`.  Whether or not that's \"valid\" for classes is less clear.  Anyways it's unlikely to occur, but safer to check for anyways.  You're right about `__qualname__`.",
    "created_at": "2017-11-24T11:15:18Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367431",
    "user": "https://github.com/embray"
}
```

<div id="comment:9" align="right">comment:9</div>

Replying to [@jdemeyer](#comment%3A7):
> 1. Why this check?
> 
> ```
> if exc_info[0].__module__
> ```
> Are there any cases where `__module__` would *not* be a `True` value?

While I can't name an exact case off the top of my head, I've seen pathological cases (especially in the context of dynamically created classes) where `__module__` can be `None`.  For functions and methods it can definitely be `None`.  Whether or not that's "valid" for classes is less clear.  Anyways it's unlikely to occur, but safer to check for anyways.  You're right about `__qualname__`.



---

archive/issue_comments_367432.json:
```json
{
    "body": "Changed commit from **[`fc905d7`](https://github.com/sagemath/sagetrac-mirror/commit/fc905d7c9b141834628cdfcc854e280e4704ceab)** to **[`90ebe89`](https://github.com/sagemath/sagetrac-mirror/commit/90ebe89df08b6bc196429818af172555f59c5c6a)**",
    "created_at": "2017-11-24T11:21:14Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367432",
    "user": "https://github.com/sagetrac-git"
}
```

Changed commit from **[`fc905d7`](https://github.com/sagemath/sagetrac-mirror/commit/fc905d7c9b141834628cdfcc854e280e4704ceab)** to **[`90ebe89`](https://github.com/sagemath/sagetrac-mirror/commit/90ebe89df08b6bc196429818af172555f59c5c6a)**



---

archive/issue_comments_367433.json:
```json
{
    "body": "<div id=\"comment:10\"></div>\n\nBranch pushed to git repo; I updated commit sha1. New commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/90ebe89df08b6bc196429818af172555f59c5c6a\"><code>90ebe89</code></a></td><td><code>* Use `__qualname__` instead of `__name__` where avaialble (i.e. Python 3)</code></td></tr></table>\n",
    "created_at": "2017-11-24T11:21:14Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367433",
    "user": "https://github.com/sagetrac-git"
}
```

<div id="comment:10"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/90ebe89df08b6bc196429818af172555f59c5c6a"><code>90ebe89</code></a></td><td><code>* Use `__qualname__` instead of `__name__` where avaialble (i.e. Python 3)</code></td></tr></table>




---

archive/issue_events_333975.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-11-24T11:21:29Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333975"
}
```



---

archive/issue_events_333976.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-11-24T11:21:29Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333976"
}
```



---

archive/issue_comments_367434.json:
```json
{
    "body": "<div id=\"comment:12\" align=\"right\">comment:12</div>\n\nAnalogously, why\n\n```\ngetattr(exc_cls, '__qualname__', exc_cls.__name__)\n```\ninstead of\n\n```\nexc_cls.__qualname__\n```\nAre there any cases where `__qualname__` wouldn't exist?\n\nFor both the `__module__` check and `__qualname__` check: the Python standard `traceback` module doesn't do anything fancy here, it just uses the `__qualname__` and `__module__` attributes as-is. If that's good enough for the `traceback` module, it should be good enough for Sage.",
    "created_at": "2017-11-24T11:30:14Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367434",
    "user": "https://github.com/jdemeyer"
}
```

<div id="comment:12" align="right">comment:12</div>

Analogously, why

```
getattr(exc_cls, '__qualname__', exc_cls.__name__)
```
instead of

```
exc_cls.__qualname__
```
Are there any cases where `__qualname__` wouldn't exist?

For both the `__module__` check and `__qualname__` check: the Python standard `traceback` module doesn't do anything fancy here, it just uses the `__qualname__` and `__module__` attributes as-is. If that's good enough for the `traceback` module, it should be good enough for Sage.



---

archive/issue_comments_367435.json:
```json
{
    "body": "<div id=\"comment:13\" align=\"right\">comment:13</div>\n\nThat specific code is run on both Python 2 and 3.  There is no `__qualname__` on Python 2.  I guess I could move all the code under a `if not six.PY2` since none of that is currently used on Python 2 anyways (it could be used though if we ever wanted to make the opposite transformation).",
    "created_at": "2017-11-24T12:07:52Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367435",
    "user": "https://github.com/embray"
}
```

<div id="comment:13" align="right">comment:13</div>

That specific code is run on both Python 2 and 3.  There is no `__qualname__` on Python 2.  I guess I could move all the code under a `if not six.PY2` since none of that is currently used on Python 2 anyways (it could be used though if we ever wanted to make the opposite transformation).



---

archive/issue_comments_367436.json:
```json
{
    "body": "<div id=\"comment:14\" align=\"right\">comment:14</div>\n\nReplying to [@embray](#comment%3A13):\n> That specific code is run on both Python 2 and 3.\n\nRight, I missed that.\n\n> I guess I could move all the code under a `if not six.PY2`\n\nThat makes sense.",
    "created_at": "2017-11-24T12:29:52Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367436",
    "user": "https://github.com/jdemeyer"
}
```

<div id="comment:14" align="right">comment:14</div>

Replying to [@embray](#comment%3A13):
> That specific code is run on both Python 2 and 3.

Right, I missed that.

> I guess I could move all the code under a `if not six.PY2`

That makes sense.



---

archive/issue_comments_367437.json:
```json
{
    "body": "<div id=\"comment:15\"></div>\n\nBranch pushed to git repo; I updated commit sha1. This was a forced push. New commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/c05196d665f48635245f65eaea5e632dd8f0b53e\"><code>c05196d</code></a></td><td><code>Better support on Python 3 for doctests that expect exceptions.</code></td></tr></table>\n",
    "created_at": "2017-11-27T09:56:51Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367437",
    "user": "https://github.com/sagetrac-git"
}
```

<div id="comment:15"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/c05196d665f48635245f65eaea5e632dd8f0b53e"><code>c05196d</code></a></td><td><code>Better support on Python 3 for doctests that expect exceptions.</code></td></tr></table>




---

archive/issue_comments_367438.json:
```json
{
    "body": "Changed commit from **[`90ebe89`](https://github.com/sagemath/sagetrac-mirror/commit/90ebe89df08b6bc196429818af172555f59c5c6a)** to **[`c05196d`](https://github.com/sagemath/sagetrac-mirror/commit/c05196d665f48635245f65eaea5e632dd8f0b53e)**",
    "created_at": "2017-11-27T09:56:51Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367438",
    "user": "https://github.com/sagetrac-git"
}
```

Changed commit from **[`90ebe89`](https://github.com/sagemath/sagetrac-mirror/commit/90ebe89df08b6bc196429818af172555f59c5c6a)** to **[`c05196d`](https://github.com/sagemath/sagetrac-mirror/commit/c05196d665f48635245f65eaea5e632dd8f0b53e)**



---

archive/issue_comments_367439.json:
```json
{
    "body": "<div id=\"comment:16\" align=\"right\">comment:16</div>\n\nFixed up a bit more and squashed.",
    "created_at": "2017-11-27T13:13:51Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367439",
    "user": "https://github.com/embray"
}
```

<div id="comment:16" align="right">comment:16</div>

Fixed up a bit more and squashed.



---

archive/issue_comments_367440.json:
```json
{
    "body": "<div id=\"comment:17\" align=\"right\">comment:17</div>\n\nActually, I just noticed one other little thing that would be nice to add to this.",
    "created_at": "2017-11-27T13:27:51Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367440",
    "user": "https://github.com/embray"
}
```

<div id="comment:17" align="right">comment:17</div>

Actually, I just noticed one other little thing that would be nice to add to this.



---

archive/issue_events_333977.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-11-27T13:27:51Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333977"
}
```



---

archive/issue_events_333978.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-11-27T13:27:51Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333978"
}
```



---

archive/issue_comments_367441.json:
```json
{
    "body": "<div id=\"comment:18\"></div>\n\nBranch pushed to git repo; I updated commit sha1. New commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/9a659d831cb431c6884d22c715fecc4cda9a6b61\"><code>9a659d8</code></a></td><td><code>Handle some common (particularly IOError) exceptions that are just aliases of</code></td></tr></table>\n",
    "created_at": "2017-11-27T13:33:54Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367441",
    "user": "https://github.com/sagetrac-git"
}
```

<div id="comment:18"></div>

Branch pushed to git repo; I updated commit sha1. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9a659d831cb431c6884d22c715fecc4cda9a6b61"><code>9a659d8</code></a></td><td><code>Handle some common (particularly IOError) exceptions that are just aliases of</code></td></tr></table>




---

archive/issue_comments_367442.json:
```json
{
    "body": "Changed commit from **[`c05196d`](https://github.com/sagemath/sagetrac-mirror/commit/c05196d665f48635245f65eaea5e632dd8f0b53e)** to **[`9a659d8`](https://github.com/sagemath/sagetrac-mirror/commit/9a659d831cb431c6884d22c715fecc4cda9a6b61)**",
    "created_at": "2017-11-27T13:33:54Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367442",
    "user": "https://github.com/sagetrac-git"
}
```

Changed commit from **[`c05196d`](https://github.com/sagemath/sagetrac-mirror/commit/c05196d665f48635245f65eaea5e632dd8f0b53e)** to **[`9a659d8`](https://github.com/sagemath/sagetrac-mirror/commit/9a659d831cb431c6884d22c715fecc4cda9a6b61)**



---

archive/issue_comments_367443.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -12,6 +12,8 @@\n \n Therefore any doctest that expects a traceback fails, due to this slight formatting difference.  One can go through all such tests and insert ellipses.  But it's simpler if we just normalize for this trivial formatting difference, similarly to #24258.\n \n-In this case it isn't done directly in the `OutputChecker` since, in order to make this normalization as restrictive as possible, we need access to the exception info which is not normally passed to `OutputChecker`.  So this is handled directly in `SageDocTestRunner`'s result handling.\n+Additionally, there were a few common exceptions (particularly `IOError` which [as of Python 3.3](https://docs.python.org/3/library/exceptions.html#OSError) are just aliases for `OSError`, so we handle that case as well.\n+\n+In this case the fixup isn't done directly in the `OutputChecker` since, in order to make this normalization as restrictive as possible, we need access to the exception info which is not normally passed to `OutputChecker`.  So this is handled directly in `SageDocTestRunner`'s result handling.\n \n This made a lot of previously \"failing\" tests pass for me.  But it should be made clear that this normalization does not in any way take away from the validity of the tests.\n``````\n",
    "created_at": "2017-11-27T13:35:17Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367443",
    "user": "https://github.com/embray"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -12,6 +12,8 @@
 
 Therefore any doctest that expects a traceback fails, due to this slight formatting difference.  One can go through all such tests and insert ellipses.  But it's simpler if we just normalize for this trivial formatting difference, similarly to #24258.
 
-In this case it isn't done directly in the `OutputChecker` since, in order to make this normalization as restrictive as possible, we need access to the exception info which is not normally passed to `OutputChecker`.  So this is handled directly in `SageDocTestRunner`'s result handling.
+Additionally, there were a few common exceptions (particularly `IOError` which [as of Python 3.3](https://docs.python.org/3/library/exceptions.html#OSError) are just aliases for `OSError`, so we handle that case as well.
+
+In this case the fixup isn't done directly in the `OutputChecker` since, in order to make this normalization as restrictive as possible, we need access to the exception info which is not normally passed to `OutputChecker`.  So this is handled directly in `SageDocTestRunner`'s result handling.
 
 This made a lot of previously "failing" tests pass for me.  But it should be made clear that this normalization does not in any way take away from the validity of the tests.
``````




---

archive/issue_comments_367444.json:
```json
{
    "body": "<div id=\"comment:19\"></div>\n\nNew commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/9a659d831cb431c6884d22c715fecc4cda9a6b61\"><code>9a659d8</code></a></td><td><code>Handle some common (particularly IOError) exceptions that are just aliases of</code></td></tr></table>\n",
    "created_at": "2017-11-27T13:35:17Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367444",
    "user": "https://github.com/embray"
}
```

<div id="comment:19"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/9a659d831cb431c6884d22c715fecc4cda9a6b61"><code>9a659d8</code></a></td><td><code>Handle some common (particularly IOError) exceptions that are just aliases of</code></td></tr></table>




---

archive/issue_events_333979.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-11-27T13:35:17Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333979"
}
```



---

archive/issue_events_333980.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-11-27T13:35:17Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333980"
}
```



---

archive/issue_comments_367445.json:
```json
{
    "body": "Reviewer: **Jeroen Demeyer**",
    "created_at": "2017-11-28T13:31:24Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367445",
    "user": "https://github.com/jdemeyer"
}
```

Reviewer: **Jeroen Demeyer**



---

archive/issue_events_333981.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-11-28T13:31:24Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333981"
}
```



---

archive/issue_events_333982.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2017-11-28T13:31:24Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333982"
}
```



---

archive/issue_events_333983.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-12-12T08:27:24Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "milestone_number": null,
    "milestone_title": "sage-8.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333983"
}
```



---

archive/issue_events_333984.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2017-12-12T08:27:24Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "milestone_number": null,
    "milestone_title": "sage-8.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333984"
}
```



---

archive/issue_comments_367446.json:
```json
{
    "body": "Changed branch from **[u/embray/python3/doctest-exceptions](https://github.com/sagemath/sagetrac-mirror/tree/u/embray/python3/doctest-exceptions)** to **[`9a659d8`](https://github.com/sagemath/sagetrac-mirror/commit/9a659d831cb431c6884d22c715fecc4cda9a6b61)**",
    "created_at": "2017-12-13T17:38:05Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24271#issuecomment-367446",
    "user": "https://github.com/vbraun"
}
```

Changed branch from **[u/embray/python3/doctest-exceptions](https://github.com/sagemath/sagetrac-mirror/tree/u/embray/python3/doctest-exceptions)** to **[`9a659d8`](https://github.com/sagemath/sagetrac-mirror/commit/9a659d831cb431c6884d22c715fecc4cda9a6b61)**



---

archive/issue_events_333985.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2017-12-13T17:38:05Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333985"
}
```



---

archive/issue_events_333986.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "b797dd7dc47ffdd9d1f4b610a2316c66bc3665e0",
    "commit_repository": "https://github.com/sagemath/sage",
    "created_at": "2017-12-13T17:38:05Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/24271",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24271#event-333986"
}
```
