# Issue 24379: Matplotlib on Python 2 bugs out when there are non-ASCII characters in user's home directory

archive/issues_024142.json:
```json
{
    "body": "The `matplotlib/__init__.py` module contains `from `__future__` import unicode_literals` which is often inadvisable, as it can run afoul of some of Python's own unicode bugs.\n\nIn particular at one point it calls `os.path.expanduser('~')`, where because of `unicode_literals` this becomes `os.path.expanduser(u'~')`.  This does not take care to decode the results of `os.environ['HOME']` (assuming it is ASCII), and ends up concatenating a unicode string with a non-unicode string, which means trying to first decoded the non-unicode string with the default (ASCII) encoding.\n\nThis is a bug in matplotlib but it affects Sage users, particularly on Windows where non-ASCII usernames are more common (may also affect OSX users): https://ask.sagemath.org/question/40131/sagemath-80-using-windows-installer\n\n**Upstream report:** https://github.com/matplotlib/matplotlib/issues/10017\n\nDepends on #25702\n\n**CC:**  @slel epalezzato\n\n**Keywords:** matplotlib, days94\n\n**Upstream:** Fixed upstream, in a later stable release.\n\n**Reviewer:** Erik Bray\n\nIssue created by migration from https://trac.sagemath.org/ticket/24379\n\n",
    "closed_at": "2018-10-31T12:07:09Z",
    "created_at": "2017-12-15T10:20:06Z",
    "labels": [
        "component: packages: standard",
        "bug",
        "worksforme",
        "invalid"
    ],
    "title": "Matplotlib on Python 2 bugs out when there are non-ASCII characters in user's home directory",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/24379",
    "user": "https://github.com/embray"
}
```
The `matplotlib/__init__.py` module contains `from `__future__` import unicode_literals` which is often inadvisable, as it can run afoul of some of Python's own unicode bugs.

In particular at one point it calls `os.path.expanduser('~')`, where because of `unicode_literals` this becomes `os.path.expanduser(u'~')`.  This does not take care to decode the results of `os.environ['HOME']` (assuming it is ASCII), and ends up concatenating a unicode string with a non-unicode string, which means trying to first decoded the non-unicode string with the default (ASCII) encoding.

This is a bug in matplotlib but it affects Sage users, particularly on Windows where non-ASCII usernames are more common (may also affect OSX users): https://ask.sagemath.org/question/40131/sagemath-80-using-windows-installer

**Upstream report:** https://github.com/matplotlib/matplotlib/issues/10017

Depends on #25702

**CC:**  @slel epalezzato

**Keywords:** matplotlib, days94

**Upstream:** Fixed upstream, in a later stable release.

**Reviewer:** Erik Bray

Issue created by migration from https://trac.sagemath.org/ticket/24379





---

archive/issue_comments_371879.json:
```json
{
    "body": "<a id='comment:1'></a>\nIt looks like it is still present in the latest release (2.1.0), for which I have been working on an upgrade at #23696.\n\n```\nfrom __future__ import (absolute_import, division, print_function,\n                        unicode_literals)\n```",
    "created_at": "2017-12-15T18:03:33Z",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24379#issuecomment-371879",
    "user": "https://github.com/kiwifb"
}
```

<a id='comment:1'></a>
It looks like it is still present in the latest release (2.1.0), for which I have been working on an upgrade at #23696.

```
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
```



---

archive/issue_comments_371880.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -3,3 +3,5 @@\n In particular at one point it calls `os.path.expanduser('~')`, where because of `unicode_literals` this becomes `os.path.expanduser(u'~')`.  This does not take care to decode the results of `os.environ['HOME']` (assuming it is ASCII), and ends up concatenating a unicode string with a non-unicode string, which means trying to first decoded the non-unicode string with the default (ASCII) encoding.\n \n This is a bug in matplotlib but it affects Sage users, particularly on Windows where non-ASCII usernames are more common (may also affect OSX users): https://ask.sagemath.org/question/40131/sagemath-80-using-windows-installer\n+\n+**Upstream report:** https://github.com/matplotlib/matplotlib/issues/10017\n``````\n",
    "created_at": "2017-12-19T10:42:27Z",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24379#issuecomment-371880",
    "user": "https://github.com/embray"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -3,3 +3,5 @@
 In particular at one point it calls `os.path.expanduser('~')`, where because of `unicode_literals` this becomes `os.path.expanduser(u'~')`.  This does not take care to decode the results of `os.environ['HOME']` (assuming it is ASCII), and ends up concatenating a unicode string with a non-unicode string, which means trying to first decoded the non-unicode string with the default (ASCII) encoding.
 
 This is a bug in matplotlib but it affects Sage users, particularly on Windows where non-ASCII usernames are more common (may also affect OSX users): https://ask.sagemath.org/question/40131/sagemath-80-using-windows-installer
+
+**Upstream report:** https://github.com/matplotlib/matplotlib/issues/10017
``````




---

archive/issue_comments_371881.json:
```json
{
    "body": "**Changing upstream** from \"Not yet reported upstream; Will do shortly.\" to \"Reported upstream. No feedback yet.\".",
    "created_at": "2017-12-19T10:42:27Z",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24379#issuecomment-371881",
    "user": "https://github.com/embray"
}
```

**Changing upstream** from "Not yet reported upstream; Will do shortly." to "Reported upstream. No feedback yet.".



---

archive/issue_events_218418.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-04-26T12:13:55Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "milestone": "sage-8.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24379#event-218418"
}
```



---

archive/issue_events_218419.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-04-26T12:13:55Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "milestone": "sage-8.3",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24379#event-218419"
}
```



---

archive/issue_comments_371882.json:
```json
{
    "body": "**Changing upstream** from \"Reported upstream. No feedback yet.\" to \"Fixed upstream, in a later stable release.\".",
    "created_at": "2018-06-29T14:12:21Z",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24379#issuecomment-371882",
    "user": "https://trac.sagemath.org/admin/accounts/users/epalezzato"
}
```

**Changing upstream** from "Reported upstream. No feedback yet." to "Fixed upstream, in a later stable release.".



---

archive/issue_comments_371883.json:
```json
{
    "body": "<a id='comment:4'></a>\nThis should be solved by upgrading to matplotlib 2.2.2 which has the upstream fix.",
    "created_at": "2018-06-29T14:12:21Z",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24379#issuecomment-371883",
    "user": "https://trac.sagemath.org/admin/accounts/users/epalezzato"
}
```

<a id='comment:4'></a>
This should be solved by upgrading to matplotlib 2.2.2 which has the upstream fix.



---

archive/issue_comments_371884.json:
```json
{
    "body": "**Changing keywords** from \"\" to \"matplotlib, days94\".",
    "created_at": "2018-06-29T14:12:21Z",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24379#issuecomment-371884",
    "user": "https://trac.sagemath.org/admin/accounts/users/epalezzato"
}
```

**Changing keywords** from "" to "matplotlib, days94".



---

archive/issue_comments_371885.json:
```json
{
    "body": "**Dependencies:** #25702",
    "created_at": "2018-06-29T14:12:21Z",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24379#issuecomment-371885",
    "user": "https://trac.sagemath.org/admin/accounts/users/epalezzato"
}
```

**Dependencies:** #25702



---

archive/issue_events_218420.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-07-18T11:56:06Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "milestone": "sage-8.3",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24379#event-218420"
}
```



---

archive/issue_events_218421.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-07-18T11:56:06Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "milestone": "sage-8.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24379#event-218421"
}
```



---

archive/issue_events_218422.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-10-28T11:41:42Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "milestone": "sage-8.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24379#event-218422"
}
```



---

archive/issue_events_218423.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-10-28T11:41:42Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "milestone": "sage-8.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24379#event-218423"
}
```



---

archive/issue_comments_371886.json:
```json
{
    "body": "**Author:** Fran\u00e7ois Bissey",
    "created_at": "2018-10-31T00:48:42Z",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24379#issuecomment-371886",
    "user": "https://github.com/kiwifb"
}
```

**Author:** François Bissey



---

archive/issue_events_218424.json:
```json
{
    "actor": "https://github.com/kiwifb",
    "created_at": "2018-10-31T00:48:42Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24379#event-218424"
}
```



---

archive/issue_comments_371887.json:
```json
{
    "body": "<a id='comment:7'></a>\nThis is arguably fixed by #25702 (upgrade to MPL 2.2.2 with the fix).",
    "created_at": "2018-10-31T00:48:42Z",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24379#issuecomment-371887",
    "user": "https://github.com/kiwifb"
}
```

<a id='comment:7'></a>
This is arguably fixed by #25702 (upgrade to MPL 2.2.2 with the fix).



---

archive/issue_events_218425.json:
```json
{
    "actor": "https://github.com/kiwifb",
    "created_at": "2018-10-31T00:48:42Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "milestone": "sage-8.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24379#event-218425"
}
```



---

archive/issue_events_218426.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-10-31T12:07:09Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24379#event-218426"
}
```



---

archive/issue_events_218427.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-10-31T12:07:09Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24379#event-218427"
}
```



---

archive/issue_comments_371888.json:
```json
{
    "body": "<a id='comment:8'></a>\nYep; IIRC this was fixed, thanks for the triaging.",
    "created_at": "2018-10-31T12:07:09Z",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24379#issuecomment-371888",
    "user": "https://github.com/embray"
}
```

<a id='comment:8'></a>
Yep; IIRC this was fixed, thanks for the triaging.



---

archive/issue_events_218428.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-10-31T12:07:09Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "label": "worksforme",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/24379#event-218428"
}
```



---

archive/issue_comments_371889.json:
```json
{
    "body": "**Changing author** from \"Fran\u00e7ois Bissey\" to \"\".",
    "created_at": "2018-11-01T13:43:05Z",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24379#issuecomment-371889",
    "user": "https://github.com/slel"
}
```

**Changing author** from "François Bissey" to "".



---

archive/issue_comments_371890.json:
```json
{
    "body": "**Reviewer:** Erik Bray",
    "created_at": "2018-11-01T13:43:05Z",
    "issue": "https://github.com/sagemath/sage/issues/24379",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/24379#issuecomment-371890",
    "user": "https://github.com/slel"
}
```

**Reviewer:** Erik Bray
